package com.pojo;

// Generated 27 Feb, 2017 10:54:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Division generated by hbm2java
 */
public class Division implements java.io.Serializable {

	private Integer divId;
	private String divName;
	private Set studentdetails = new HashSet(0);

	public Division() {
	}

	public Division(String divName, Set studentdetails) {
		this.divName = divName;
		this.studentdetails = studentdetails;
	}

	public Integer getDivId() {
		return this.divId;
	}

	public void setDivId(Integer divId) {
		this.divId = divId;
	}

	public String getDivName() {
		return this.divName;
	}

	public void setDivName(String divName) {
		this.divName = divName;
	}

	public Set getStudentdetails() {
		return this.studentdetails;
	}

	public void setStudentdetails(Set studentdetails) {
		this.studentdetails = studentdetails;
	}

}
