package com.pojo;

// Generated 27 Feb, 2017 10:54:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Notice generated by hbm2java
 */
public class Notice implements java.io.Serializable {

	private Integer noticeId;
	private Teacherdetail teacherdetail;
	private Classdetail classdetail;
	private Date noticeDate;
	private String noticeDescription;

	public Notice() {
	}

	public Notice(Teacherdetail teacherdetail, Classdetail classdetail,
			Date noticeDate, String noticeDescription) {
		this.teacherdetail = teacherdetail;
		this.classdetail = classdetail;
		this.noticeDate = noticeDate;
		this.noticeDescription = noticeDescription;
	}

	public Integer getNoticeId() {
		return this.noticeId;
	}

	public void setNoticeId(Integer noticeId) {
		this.noticeId = noticeId;
	}

	public Teacherdetail getTeacherdetail() {
		return this.teacherdetail;
	}

	public void setTeacherdetail(Teacherdetail teacherdetail) {
		this.teacherdetail = teacherdetail;
	}

	public Classdetail getClassdetail() {
		return this.classdetail;
	}

	public void setClassdetail(Classdetail classdetail) {
		this.classdetail = classdetail;
	}

	public Date getNoticeDate() {
		return this.noticeDate;
	}

	public void setNoticeDate(Date noticeDate) {
		this.noticeDate = noticeDate;
	}

	public String getNoticeDescription() {
		return this.noticeDescription;
	}

	public void setNoticeDescription(String noticeDescription) {
		this.noticeDescription = noticeDescription;
	}

}
