package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Integer addressId;
	private String currentAddress;
	private String currentStreet;
	private String currentCity;
	private Integer currentZipCode;
	private String currentState;
	private String currentCountry;
	private String permanentAddress;
	private String permanentStrret;
	private String permanentCity;
	private Integer permanentZipCode;
	private String permanentState;
	private String permanentCountry;
	private Long mobileNumber;
	private Long alternateMobileNumber;
	private Set applicationforadmissions = new HashSet(0);

	public Address() {
	}

	public Address(String currentAddress, String currentStreet, String currentCity, Integer currentZipCode,
			String currentState, String currentCountry, String permanentAddress, String permanentStrret,
			String permanentCity, Integer permanentZipCode, String permanentState, String permanentCountry,
			Long mobileNumber, Long alternateMobileNumber, Set applicationforadmissions) {
		this.currentAddress = currentAddress;
		this.currentStreet = currentStreet;
		this.currentCity = currentCity;
		this.currentZipCode = currentZipCode;
		this.currentState = currentState;
		this.currentCountry = currentCountry;
		this.permanentAddress = permanentAddress;
		this.permanentStrret = permanentStrret;
		this.permanentCity = permanentCity;
		this.permanentZipCode = permanentZipCode;
		this.permanentState = permanentState;
		this.permanentCountry = permanentCountry;
		this.mobileNumber = mobileNumber;
		this.alternateMobileNumber = alternateMobileNumber;
		this.applicationforadmissions = applicationforadmissions;
	}

	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public String getCurrentAddress() {
		return this.currentAddress;
	}

	public void setCurrentAddress(String currentAddress) {
		this.currentAddress = currentAddress;
	}

	public String getCurrentStreet() {
		return this.currentStreet;
	}

	public void setCurrentStreet(String currentStreet) {
		this.currentStreet = currentStreet;
	}

	public String getCurrentCity() {
		return this.currentCity;
	}

	public void setCurrentCity(String currentCity) {
		this.currentCity = currentCity;
	}

	public Integer getCurrentZipCode() {
		return this.currentZipCode;
	}

	public void setCurrentZipCode(Integer currentZipCode) {
		this.currentZipCode = currentZipCode;
	}

	public String getCurrentState() {
		return this.currentState;
	}

	public void setCurrentState(String currentState) {
		this.currentState = currentState;
	}

	public String getCurrentCountry() {
		return this.currentCountry;
	}

	public void setCurrentCountry(String currentCountry) {
		this.currentCountry = currentCountry;
	}

	public String getPermanentAddress() {
		return this.permanentAddress;
	}

	public void setPermanentAddress(String permanentAddress) {
		this.permanentAddress = permanentAddress;
	}

	public String getPermanentStrret() {
		return this.permanentStrret;
	}

	public void setPermanentStrret(String permanentStrret) {
		this.permanentStrret = permanentStrret;
	}

	public String getPermanentCity() {
		return this.permanentCity;
	}

	public void setPermanentCity(String permanentCity) {
		this.permanentCity = permanentCity;
	}

	public Integer getPermanentZipCode() {
		return this.permanentZipCode;
	}

	public void setPermanentZipCode(Integer permanentZipCode) {
		this.permanentZipCode = permanentZipCode;
	}

	public String getPermanentState() {
		return this.permanentState;
	}

	public void setPermanentState(String permanentState) {
		this.permanentState = permanentState;
	}

	public String getPermanentCountry() {
		return this.permanentCountry;
	}

	public void setPermanentCountry(String permanentCountry) {
		this.permanentCountry = permanentCountry;
	}

	public Long getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(Long mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public Long getAlternateMobileNumber() {
		return this.alternateMobileNumber;
	}

	public void setAlternateMobileNumber(Long alternateMobileNumber) {
		this.alternateMobileNumber = alternateMobileNumber;
	}

	public Set getApplicationforadmissions() {
		return this.applicationforadmissions;
	}

	public void setApplicationforadmissions(Set applicationforadmissions) {
		this.applicationforadmissions = applicationforadmissions;
	}

}
