package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Admissionprocess generated by hbm2java
 */
public class Admissionprocess implements java.io.Serializable {

	private Integer admissionProcessId;
	private Admissionyear admissionyear;
	private Date admissionStartDate;
	private Date admissionEndDate;

	public Admissionprocess() {
	}

	public Admissionprocess(Admissionyear admissionyear, Date admissionStartDate, Date admissionEndDate) {
		this.admissionyear = admissionyear;
		this.admissionStartDate = admissionStartDate;
		this.admissionEndDate = admissionEndDate;
	}

	public Integer getAdmissionProcessId() {
		return this.admissionProcessId;
	}

	public void setAdmissionProcessId(Integer admissionProcessId) {
		this.admissionProcessId = admissionProcessId;
	}

	public Admissionyear getAdmissionyear() {
		return this.admissionyear;
	}

	public void setAdmissionyear(Admissionyear admissionyear) {
		this.admissionyear = admissionyear;
	}

	public Date getAdmissionStartDate() {
		return this.admissionStartDate;
	}

	public void setAdmissionStartDate(Date admissionStartDate) {
		this.admissionStartDate = admissionStartDate;
	}

	public Date getAdmissionEndDate() {
		return this.admissionEndDate;
	}

	public void setAdmissionEndDate(Date admissionEndDate) {
		this.admissionEndDate = admissionEndDate;
	}

}
