package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Admissionyear generated by hbm2java
 */
public class Admissionyear implements java.io.Serializable {

	private Integer yearId;
	private String year;
	private Set admissionprocesses = new HashSet(0);
	private Set enrolledstudentses = new HashSet(0);
	private Set enrolledstudentses_1 = new HashSet(0);
	private Set cancelledstudentses = new HashSet(0);
	private Set cancelledstudentses_1 = new HashSet(0);
	private Set admissionprocesses_1 = new HashSet(0);

	public Admissionyear() {
	}

	public Admissionyear(String year, Set admissionprocesses, Set enrolledstudentses, Set enrolledstudentses_1,
			Set cancelledstudentses, Set cancelledstudentses_1, Set admissionprocesses_1) {
		this.year = year;
		this.admissionprocesses = admissionprocesses;
		this.enrolledstudentses = enrolledstudentses;
		this.enrolledstudentses_1 = enrolledstudentses_1;
		this.cancelledstudentses = cancelledstudentses;
		this.cancelledstudentses_1 = cancelledstudentses_1;
		this.admissionprocesses_1 = admissionprocesses_1;
	}

	public Integer getYearId() {
		return this.yearId;
	}

	public void setYearId(Integer yearId) {
		this.yearId = yearId;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public Set getAdmissionprocesses() {
		return this.admissionprocesses;
	}

	public void setAdmissionprocesses(Set admissionprocesses) {
		this.admissionprocesses = admissionprocesses;
	}

	public Set getEnrolledstudentses() {
		return this.enrolledstudentses;
	}

	public void setEnrolledstudentses(Set enrolledstudentses) {
		this.enrolledstudentses = enrolledstudentses;
	}

	public Set getEnrolledstudentses_1() {
		return this.enrolledstudentses_1;
	}

	public void setEnrolledstudentses_1(Set enrolledstudentses_1) {
		this.enrolledstudentses_1 = enrolledstudentses_1;
	}

	public Set getCancelledstudentses() {
		return this.cancelledstudentses;
	}

	public void setCancelledstudentses(Set cancelledstudentses) {
		this.cancelledstudentses = cancelledstudentses;
	}

	public Set getCancelledstudentses_1() {
		return this.cancelledstudentses_1;
	}

	public void setCancelledstudentses_1(Set cancelledstudentses_1) {
		this.cancelledstudentses_1 = cancelledstudentses_1;
	}

	public Set getAdmissionprocesses_1() {
		return this.admissionprocesses_1;
	}

	public void setAdmissionprocesses_1(Set admissionprocesses_1) {
		this.admissionprocesses_1 = admissionprocesses_1;
	}

}
