package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Adminaddinventory generated by hbm2java
 */
public class Adminaddinventory implements java.io.Serializable {

	private Integer adminAddInventoryId;
	private Inventoryrequest inventoryrequest;
	private Integer receivedQuantity;
	private Date receivedItemsDate;

	public Adminaddinventory() {
	}

	public Adminaddinventory(Inventoryrequest inventoryrequest, Integer receivedQuantity, Date receivedItemsDate) {
		this.inventoryrequest = inventoryrequest;
		this.receivedQuantity = receivedQuantity;
		this.receivedItemsDate = receivedItemsDate;
	}

	public Integer getAdminAddInventoryId() {
		return this.adminAddInventoryId;
	}

	public void setAdminAddInventoryId(Integer adminAddInventoryId) {
		this.adminAddInventoryId = adminAddInventoryId;
	}

	public Inventoryrequest getInventoryrequest() {
		return this.inventoryrequest;
	}

	public void setInventoryrequest(Inventoryrequest inventoryrequest) {
		this.inventoryrequest = inventoryrequest;
	}

	public Integer getReceivedQuantity() {
		return this.receivedQuantity;
	}

	public void setReceivedQuantity(Integer receivedQuantity) {
		this.receivedQuantity = receivedQuantity;
	}

	public Date getReceivedItemsDate() {
		return this.receivedItemsDate;
	}

	public void setReceivedItemsDate(Date receivedItemsDate) {
		this.receivedItemsDate = receivedItemsDate;
	}

}
