package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Applicationforadmission generated by hbm2java
 */
public class Applicationforadmission implements java.io.Serializable {

	private Integer applicationId;
	private Bachelordetail bachelordetail;
	private Sscdetail sscdetail;
	private Course course;
	private Masterdetail masterdetail;
	private Branch branch;
	private Diplomadetail diplomadetail;
	private Registration registration;
	private Uploadeddocuments uploadeddocuments;
	private Hscdetail hscdetail;
	private Address address;
	private String applicantFirstName;
	private String applicantMiddleName;
	private String applicantLastName;
	private Date applicantDob;
	private Integer applicantAge;
	private String applicatantEmailId;
	private String applicantNativePlace;
	private String applicantGender;
	private String applicantBloodgroup;
	private String applicantMotherTongue;
	private String applicatantFatherName;
	private String applicatantFatherOccupation;
	private String applicatantMotherName;
	private String applicatantMotherOccupation;
	private Double annualIncome;
	private String applicatantNationality;
	private String applicatantReligion;
	private String applicatantCaste;
	private String applicatantCategory;
	private String hostelFacility;
	private String transportationFacility;
	private Date dateTime;
	private Integer approvalStatus;
	private Set cancelledstudentses = new HashSet(0);
	private Set studentfeespayments = new HashSet(0);
	private Set enrolledstudentses = new HashSet(0);
	private Set studentadmitnfeeses = new HashSet(0);
	private Set hostelregistrations = new HashSet(0);
	private Set enrolledstudentses_1 = new HashSet(0);
	private Set cancelledstudentses_1 = new HashSet(0);

	public Applicationforadmission() {
	}

	public Applicationforadmission(Bachelordetail bachelordetail, Sscdetail sscdetail, Course course,
			Masterdetail masterdetail, Branch branch, Diplomadetail diplomadetail, Registration registration,
			Uploadeddocuments uploadeddocuments, Hscdetail hscdetail, Address address, String applicantFirstName,
			String applicantMiddleName, String applicantLastName, Date applicantDob, Integer applicantAge,
			String applicatantEmailId, String applicantNativePlace, String applicantGender, String applicantBloodgroup,
			String applicantMotherTongue, String applicatantFatherName, String applicatantFatherOccupation,
			String applicatantMotherName, String applicatantMotherOccupation, Double annualIncome,
			String applicatantNationality, String applicatantReligion, String applicatantCaste,
			String applicatantCategory, String hostelFacility, String transportationFacility, Date dateTime,
			Integer approvalStatus, Set cancelledstudentses, Set studentfeespayments, Set enrolledstudentses,
			Set studentadmitnfeeses, Set hostelregistrations, Set enrolledstudentses_1, Set cancelledstudentses_1) {
		this.bachelordetail = bachelordetail;
		this.sscdetail = sscdetail;
		this.course = course;
		this.masterdetail = masterdetail;
		this.branch = branch;
		this.diplomadetail = diplomadetail;
		this.registration = registration;
		this.uploadeddocuments = uploadeddocuments;
		this.hscdetail = hscdetail;
		this.address = address;
		this.applicantFirstName = applicantFirstName;
		this.applicantMiddleName = applicantMiddleName;
		this.applicantLastName = applicantLastName;
		this.applicantDob = applicantDob;
		this.applicantAge = applicantAge;
		this.applicatantEmailId = applicatantEmailId;
		this.applicantNativePlace = applicantNativePlace;
		this.applicantGender = applicantGender;
		this.applicantBloodgroup = applicantBloodgroup;
		this.applicantMotherTongue = applicantMotherTongue;
		this.applicatantFatherName = applicatantFatherName;
		this.applicatantFatherOccupation = applicatantFatherOccupation;
		this.applicatantMotherName = applicatantMotherName;
		this.applicatantMotherOccupation = applicatantMotherOccupation;
		this.annualIncome = annualIncome;
		this.applicatantNationality = applicatantNationality;
		this.applicatantReligion = applicatantReligion;
		this.applicatantCaste = applicatantCaste;
		this.applicatantCategory = applicatantCategory;
		this.hostelFacility = hostelFacility;
		this.transportationFacility = transportationFacility;
		this.dateTime = dateTime;
		this.approvalStatus = approvalStatus;
		this.cancelledstudentses = cancelledstudentses;
		this.studentfeespayments = studentfeespayments;
		this.enrolledstudentses = enrolledstudentses;
		this.studentadmitnfeeses = studentadmitnfeeses;
		this.hostelregistrations = hostelregistrations;
		this.enrolledstudentses_1 = enrolledstudentses_1;
		this.cancelledstudentses_1 = cancelledstudentses_1;
	}

	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	public Bachelordetail getBachelordetail() {
		return this.bachelordetail;
	}

	public void setBachelordetail(Bachelordetail bachelordetail) {
		this.bachelordetail = bachelordetail;
	}

	public Sscdetail getSscdetail() {
		return this.sscdetail;
	}

	public void setSscdetail(Sscdetail sscdetail) {
		this.sscdetail = sscdetail;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Masterdetail getMasterdetail() {
		return this.masterdetail;
	}

	public void setMasterdetail(Masterdetail masterdetail) {
		this.masterdetail = masterdetail;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public Diplomadetail getDiplomadetail() {
		return this.diplomadetail;
	}

	public void setDiplomadetail(Diplomadetail diplomadetail) {
		this.diplomadetail = diplomadetail;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public Uploadeddocuments getUploadeddocuments() {
		return this.uploadeddocuments;
	}

	public void setUploadeddocuments(Uploadeddocuments uploadeddocuments) {
		this.uploadeddocuments = uploadeddocuments;
	}

	public Hscdetail getHscdetail() {
		return this.hscdetail;
	}

	public void setHscdetail(Hscdetail hscdetail) {
		this.hscdetail = hscdetail;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getApplicantFirstName() {
		return this.applicantFirstName;
	}

	public void setApplicantFirstName(String applicantFirstName) {
		this.applicantFirstName = applicantFirstName;
	}

	public String getApplicantMiddleName() {
		return this.applicantMiddleName;
	}

	public void setApplicantMiddleName(String applicantMiddleName) {
		this.applicantMiddleName = applicantMiddleName;
	}

	public String getApplicantLastName() {
		return this.applicantLastName;
	}

	public void setApplicantLastName(String applicantLastName) {
		this.applicantLastName = applicantLastName;
	}

	public Date getApplicantDob() {
		return this.applicantDob;
	}

	public void setApplicantDob(Date applicantDob) {
		this.applicantDob = applicantDob;
	}

	public Integer getApplicantAge() {
		return this.applicantAge;
	}

	public void setApplicantAge(Integer applicantAge) {
		this.applicantAge = applicantAge;
	}

	public String getApplicatantEmailId() {
		return this.applicatantEmailId;
	}

	public void setApplicatantEmailId(String applicatantEmailId) {
		this.applicatantEmailId = applicatantEmailId;
	}

	public String getApplicantNativePlace() {
		return this.applicantNativePlace;
	}

	public void setApplicantNativePlace(String applicantNativePlace) {
		this.applicantNativePlace = applicantNativePlace;
	}

	public String getApplicantGender() {
		return this.applicantGender;
	}

	public void setApplicantGender(String applicantGender) {
		this.applicantGender = applicantGender;
	}

	public String getApplicantBloodgroup() {
		return this.applicantBloodgroup;
	}

	public void setApplicantBloodgroup(String applicantBloodgroup) {
		this.applicantBloodgroup = applicantBloodgroup;
	}

	public String getApplicantMotherTongue() {
		return this.applicantMotherTongue;
	}

	public void setApplicantMotherTongue(String applicantMotherTongue) {
		this.applicantMotherTongue = applicantMotherTongue;
	}

	public String getApplicatantFatherName() {
		return this.applicatantFatherName;
	}

	public void setApplicatantFatherName(String applicatantFatherName) {
		this.applicatantFatherName = applicatantFatherName;
	}

	public String getApplicatantFatherOccupation() {
		return this.applicatantFatherOccupation;
	}

	public void setApplicatantFatherOccupation(String applicatantFatherOccupation) {
		this.applicatantFatherOccupation = applicatantFatherOccupation;
	}

	public String getApplicatantMotherName() {
		return this.applicatantMotherName;
	}

	public void setApplicatantMotherName(String applicatantMotherName) {
		this.applicatantMotherName = applicatantMotherName;
	}

	public String getApplicatantMotherOccupation() {
		return this.applicatantMotherOccupation;
	}

	public void setApplicatantMotherOccupation(String applicatantMotherOccupation) {
		this.applicatantMotherOccupation = applicatantMotherOccupation;
	}

	public Double getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(Double annualIncome) {
		this.annualIncome = annualIncome;
	}

	public String getApplicatantNationality() {
		return this.applicatantNationality;
	}

	public void setApplicatantNationality(String applicatantNationality) {
		this.applicatantNationality = applicatantNationality;
	}

	public String getApplicatantReligion() {
		return this.applicatantReligion;
	}

	public void setApplicatantReligion(String applicatantReligion) {
		this.applicatantReligion = applicatantReligion;
	}

	public String getApplicatantCaste() {
		return this.applicatantCaste;
	}

	public void setApplicatantCaste(String applicatantCaste) {
		this.applicatantCaste = applicatantCaste;
	}

	public String getApplicatantCategory() {
		return this.applicatantCategory;
	}

	public void setApplicatantCategory(String applicatantCategory) {
		this.applicatantCategory = applicatantCategory;
	}

	public String getHostelFacility() {
		return this.hostelFacility;
	}

	public void setHostelFacility(String hostelFacility) {
		this.hostelFacility = hostelFacility;
	}

	public String getTransportationFacility() {
		return this.transportationFacility;
	}

	public void setTransportationFacility(String transportationFacility) {
		this.transportationFacility = transportationFacility;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public Integer getApprovalStatus() {
		return this.approvalStatus;
	}

	public void setApprovalStatus(Integer approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	public Set getCancelledstudentses() {
		return this.cancelledstudentses;
	}

	public void setCancelledstudentses(Set cancelledstudentses) {
		this.cancelledstudentses = cancelledstudentses;
	}

	public Set getStudentfeespayments() {
		return this.studentfeespayments;
	}

	public void setStudentfeespayments(Set studentfeespayments) {
		this.studentfeespayments = studentfeespayments;
	}

	public Set getEnrolledstudentses() {
		return this.enrolledstudentses;
	}

	public void setEnrolledstudentses(Set enrolledstudentses) {
		this.enrolledstudentses = enrolledstudentses;
	}

	public Set getStudentadmitnfeeses() {
		return this.studentadmitnfeeses;
	}

	public void setStudentadmitnfeeses(Set studentadmitnfeeses) {
		this.studentadmitnfeeses = studentadmitnfeeses;
	}

	public Set getHostelregistrations() {
		return this.hostelregistrations;
	}

	public void setHostelregistrations(Set hostelregistrations) {
		this.hostelregistrations = hostelregistrations;
	}

	public Set getEnrolledstudentses_1() {
		return this.enrolledstudentses_1;
	}

	public void setEnrolledstudentses_1(Set enrolledstudentses_1) {
		this.enrolledstudentses_1 = enrolledstudentses_1;
	}

	public Set getCancelledstudentses_1() {
		return this.cancelledstudentses_1;
	}

	public void setCancelledstudentses_1(Set cancelledstudentses_1) {
		this.cancelledstudentses_1 = cancelledstudentses_1;
	}

}
