package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Assignment generated by hbm2java
 */
public class Assignment implements java.io.Serializable {

	private Integer assignId;
	private Teacherdetail teacherdetail;
	private String assignSubjectName;
	private Date assignDateOfStarting;
	private Date assignDateOfEnding;
	private Date assignLateSubDate;
	private String assignType;

	public Assignment() {
	}

	public Assignment(Teacherdetail teacherdetail, String assignSubjectName, Date assignDateOfStarting,
			Date assignDateOfEnding, Date assignLateSubDate, String assignType) {
		this.teacherdetail = teacherdetail;
		this.assignSubjectName = assignSubjectName;
		this.assignDateOfStarting = assignDateOfStarting;
		this.assignDateOfEnding = assignDateOfEnding;
		this.assignLateSubDate = assignLateSubDate;
		this.assignType = assignType;
	}

	public Integer getAssignId() {
		return this.assignId;
	}

	public void setAssignId(Integer assignId) {
		this.assignId = assignId;
	}

	public Teacherdetail getTeacherdetail() {
		return this.teacherdetail;
	}

	public void setTeacherdetail(Teacherdetail teacherdetail) {
		this.teacherdetail = teacherdetail;
	}

	public String getAssignSubjectName() {
		return this.assignSubjectName;
	}

	public void setAssignSubjectName(String assignSubjectName) {
		this.assignSubjectName = assignSubjectName;
	}

	public Date getAssignDateOfStarting() {
		return this.assignDateOfStarting;
	}

	public void setAssignDateOfStarting(Date assignDateOfStarting) {
		this.assignDateOfStarting = assignDateOfStarting;
	}

	public Date getAssignDateOfEnding() {
		return this.assignDateOfEnding;
	}

	public void setAssignDateOfEnding(Date assignDateOfEnding) {
		this.assignDateOfEnding = assignDateOfEnding;
	}

	public Date getAssignLateSubDate() {
		return this.assignLateSubDate;
	}

	public void setAssignLateSubDate(Date assignLateSubDate) {
		this.assignLateSubDate = assignLateSubDate;
	}

	public String getAssignType() {
		return this.assignType;
	}

	public void setAssignType(String assignType) {
		this.assignType = assignType;
	}

}
