package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Attendencetype generated by hbm2java
 */
public class Attendencetype implements java.io.Serializable {

	private Integer attendenceId;
	private String attendenceType;
	private Set hostelattendences = new HashSet(0);
	private Set studentattendances = new HashSet(0);
	private Set messattendences = new HashSet(0);
	private Set teacherattendances = new HashSet(0);

	public Attendencetype() {
	}

	public Attendencetype(String attendenceType, Set hostelattendences, Set studentattendances, Set messattendences,
			Set teacherattendances) {
		this.attendenceType = attendenceType;
		this.hostelattendences = hostelattendences;
		this.studentattendances = studentattendances;
		this.messattendences = messattendences;
		this.teacherattendances = teacherattendances;
	}

	public Integer getAttendenceId() {
		return this.attendenceId;
	}

	public void setAttendenceId(Integer attendenceId) {
		this.attendenceId = attendenceId;
	}

	public String getAttendenceType() {
		return this.attendenceType;
	}

	public void setAttendenceType(String attendenceType) {
		this.attendenceType = attendenceType;
	}

	public Set getHostelattendences() {
		return this.hostelattendences;
	}

	public void setHostelattendences(Set hostelattendences) {
		this.hostelattendences = hostelattendences;
	}

	public Set getStudentattendances() {
		return this.studentattendances;
	}

	public void setStudentattendances(Set studentattendances) {
		this.studentattendances = studentattendances;
	}

	public Set getMessattendences() {
		return this.messattendences;
	}

	public void setMessattendences(Set messattendences) {
		this.messattendences = messattendences;
	}

	public Set getTeacherattendances() {
		return this.teacherattendances;
	}

	public void setTeacherattendances(Set teacherattendances) {
		this.teacherattendances = teacherattendances;
	}

}
