package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch implements java.io.Serializable {

	private Integer branchId;
	private Course course;
	private String branchName;
	private Integer branchCode;
	private Set subjectses = new HashSet(0);
	private Set applicationforadmissions = new HashSet(0);
	private Set cancelledstudentses = new HashSet(0);
	private Set examtimetables = new HashSet(0);
	private Set cancelledstudentses_1 = new HashSet(0);
	private Set teacherdetails = new HashSet(0);
	private Set studentfeeses = new HashSet(0);
	private Set enrolledstudentses = new HashSet(0);
	private Set enrolledstudentses_1 = new HashSet(0);

	public Branch() {
	}

	public Branch(Course course, String branchName, Integer branchCode, Set subjectses, Set applicationforadmissions,
			Set cancelledstudentses, Set examtimetables, Set cancelledstudentses_1, Set teacherdetails,
			Set studentfeeses, Set enrolledstudentses, Set enrolledstudentses_1) {
		this.course = course;
		this.branchName = branchName;
		this.branchCode = branchCode;
		this.subjectses = subjectses;
		this.applicationforadmissions = applicationforadmissions;
		this.cancelledstudentses = cancelledstudentses;
		this.examtimetables = examtimetables;
		this.cancelledstudentses_1 = cancelledstudentses_1;
		this.teacherdetails = teacherdetails;
		this.studentfeeses = studentfeeses;
		this.enrolledstudentses = enrolledstudentses;
		this.enrolledstudentses_1 = enrolledstudentses_1;
	}

	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public Integer getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(Integer branchCode) {
		this.branchCode = branchCode;
	}

	public Set getSubjectses() {
		return this.subjectses;
	}

	public void setSubjectses(Set subjectses) {
		this.subjectses = subjectses;
	}

	public Set getApplicationforadmissions() {
		return this.applicationforadmissions;
	}

	public void setApplicationforadmissions(Set applicationforadmissions) {
		this.applicationforadmissions = applicationforadmissions;
	}

	public Set getCancelledstudentses() {
		return this.cancelledstudentses;
	}

	public void setCancelledstudentses(Set cancelledstudentses) {
		this.cancelledstudentses = cancelledstudentses;
	}

	public Set getExamtimetables() {
		return this.examtimetables;
	}

	public void setExamtimetables(Set examtimetables) {
		this.examtimetables = examtimetables;
	}

	public Set getCancelledstudentses_1() {
		return this.cancelledstudentses_1;
	}

	public void setCancelledstudentses_1(Set cancelledstudentses_1) {
		this.cancelledstudentses_1 = cancelledstudentses_1;
	}

	public Set getTeacherdetails() {
		return this.teacherdetails;
	}

	public void setTeacherdetails(Set teacherdetails) {
		this.teacherdetails = teacherdetails;
	}

	public Set getStudentfeeses() {
		return this.studentfeeses;
	}

	public void setStudentfeeses(Set studentfeeses) {
		this.studentfeeses = studentfeeses;
	}

	public Set getEnrolledstudentses() {
		return this.enrolledstudentses;
	}

	public void setEnrolledstudentses(Set enrolledstudentses) {
		this.enrolledstudentses = enrolledstudentses;
	}

	public Set getEnrolledstudentses_1() {
		return this.enrolledstudentses_1;
	}

	public void setEnrolledstudentses_1(Set enrolledstudentses_1) {
		this.enrolledstudentses_1 = enrolledstudentses_1;
	}

}
