package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Busandstop generated by hbm2java
 */
public class Busandstop implements java.io.Serializable {

	private Integer busAndStopId;
	private Busdetails busdetails;
	private Busstop busstop;
	private Set transportservicereqs = new HashSet(0);

	public Busandstop() {
	}

	public Busandstop(Busdetails busdetails, Busstop busstop, Set transportservicereqs) {
		this.busdetails = busdetails;
		this.busstop = busstop;
		this.transportservicereqs = transportservicereqs;
	}

	public Integer getBusAndStopId() {
		return this.busAndStopId;
	}

	public void setBusAndStopId(Integer busAndStopId) {
		this.busAndStopId = busAndStopId;
	}

	public Busdetails getBusdetails() {
		return this.busdetails;
	}

	public void setBusdetails(Busdetails busdetails) {
		this.busdetails = busdetails;
	}

	public Busstop getBusstop() {
		return this.busstop;
	}

	public void setBusstop(Busstop busstop) {
		this.busstop = busstop;
	}

	public Set getTransportservicereqs() {
		return this.transportservicereqs;
	}

	public void setTransportservicereqs(Set transportservicereqs) {
		this.transportservicereqs = transportservicereqs;
	}

}
