package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Busdetails generated by hbm2java
 */
public class Busdetails implements java.io.Serializable {

	private Integer busDetailsId;
	private Busdriver busdriver;
	private String busNumber;
	private Integer noOfSeat;
	private String busType;
	private String tripTime;
	private Set busandstops = new HashSet(0);

	public Busdetails() {
	}

	public Busdetails(Busdriver busdriver, String busNumber, Integer noOfSeat, String busType, String tripTime,
			Set busandstops) {
		this.busdriver = busdriver;
		this.busNumber = busNumber;
		this.noOfSeat = noOfSeat;
		this.busType = busType;
		this.tripTime = tripTime;
		this.busandstops = busandstops;
	}

	public Integer getBusDetailsId() {
		return this.busDetailsId;
	}

	public void setBusDetailsId(Integer busDetailsId) {
		this.busDetailsId = busDetailsId;
	}

	public Busdriver getBusdriver() {
		return this.busdriver;
	}

	public void setBusdriver(Busdriver busdriver) {
		this.busdriver = busdriver;
	}

	public String getBusNumber() {
		return this.busNumber;
	}

	public void setBusNumber(String busNumber) {
		this.busNumber = busNumber;
	}

	public Integer getNoOfSeat() {
		return this.noOfSeat;
	}

	public void setNoOfSeat(Integer noOfSeat) {
		this.noOfSeat = noOfSeat;
	}

	public String getBusType() {
		return this.busType;
	}

	public void setBusType(String busType) {
		this.busType = busType;
	}

	public String getTripTime() {
		return this.tripTime;
	}

	public void setTripTime(String tripTime) {
		this.tripTime = tripTime;
	}

	public Set getBusandstops() {
		return this.busandstops;
	}

	public void setBusandstops(Set busandstops) {
		this.busandstops = busandstops;
	}

}
