package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Busstop generated by hbm2java
 */
public class Busstop implements java.io.Serializable {

	private Integer stopId;
	private Busroute busroute;
	private String stopName;
	private Set busandstops = new HashSet(0);

	public Busstop() {
	}

	public Busstop(Busroute busroute, String stopName, Set busandstops) {
		this.busroute = busroute;
		this.stopName = stopName;
		this.busandstops = busandstops;
	}

	public Integer getStopId() {
		return this.stopId;
	}

	public void setStopId(Integer stopId) {
		this.stopId = stopId;
	}

	public Busroute getBusroute() {
		return this.busroute;
	}

	public void setBusroute(Busroute busroute) {
		this.busroute = busroute;
	}

	public String getStopName() {
		return this.stopName;
	}

	public void setStopName(String stopName) {
		this.stopName = stopName;
	}

	public Set getBusandstops() {
		return this.busandstops;
	}

	public void setBusandstops(Set busandstops) {
		this.busandstops = busandstops;
	}

}
