package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Cancelledstudents generated by hbm2java
 */
public class Cancelledstudents implements java.io.Serializable {

	private Integer cancelledStudentId;
	private Studentfees studentfees;
	private Course course;
	private Applicationforadmission applicationforadmission;
	private Branch branch;
	private Admissionyear admissionyear;
	private String enrollmentNumber;
	private Integer currentYear;
	private Double cancellationCharge;
	private Double depositeAmount;
	private Date createdDateTime;
	private Date updatedDateTime;

	public Cancelledstudents() {
	}

	public Cancelledstudents(Studentfees studentfees, Course course, Applicationforadmission applicationforadmission,
			Branch branch, Admissionyear admissionyear, String enrollmentNumber, Integer currentYear,
			Double cancellationCharge, Double depositeAmount, Date createdDateTime, Date updatedDateTime) {
		this.studentfees = studentfees;
		this.course = course;
		this.applicationforadmission = applicationforadmission;
		this.branch = branch;
		this.admissionyear = admissionyear;
		this.enrollmentNumber = enrollmentNumber;
		this.currentYear = currentYear;
		this.cancellationCharge = cancellationCharge;
		this.depositeAmount = depositeAmount;
		this.createdDateTime = createdDateTime;
		this.updatedDateTime = updatedDateTime;
	}

	public Integer getCancelledStudentId() {
		return this.cancelledStudentId;
	}

	public void setCancelledStudentId(Integer cancelledStudentId) {
		this.cancelledStudentId = cancelledStudentId;
	}

	public Studentfees getStudentfees() {
		return this.studentfees;
	}

	public void setStudentfees(Studentfees studentfees) {
		this.studentfees = studentfees;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Applicationforadmission getApplicationforadmission() {
		return this.applicationforadmission;
	}

	public void setApplicationforadmission(Applicationforadmission applicationforadmission) {
		this.applicationforadmission = applicationforadmission;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public Admissionyear getAdmissionyear() {
		return this.admissionyear;
	}

	public void setAdmissionyear(Admissionyear admissionyear) {
		this.admissionyear = admissionyear;
	}

	public String getEnrollmentNumber() {
		return this.enrollmentNumber;
	}

	public void setEnrollmentNumber(String enrollmentNumber) {
		this.enrollmentNumber = enrollmentNumber;
	}

	public Integer getCurrentYear() {
		return this.currentYear;
	}

	public void setCurrentYear(Integer currentYear) {
		this.currentYear = currentYear;
	}

	public Double getCancellationCharge() {
		return this.cancellationCharge;
	}

	public void setCancellationCharge(Double cancellationCharge) {
		this.cancellationCharge = cancellationCharge;
	}

	public Double getDepositeAmount() {
		return this.depositeAmount;
	}

	public void setDepositeAmount(Double depositeAmount) {
		this.depositeAmount = depositeAmount;
	}

	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	public Date getUpdatedDateTime() {
		return this.updatedDateTime;
	}

	public void setUpdatedDateTime(Date updatedDateTime) {
		this.updatedDateTime = updatedDateTime;
	}

}
