package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Canceledadmission generated by hbm2java
 */
public class Canceledadmission implements java.io.Serializable {

	private Integer cancellationId;
	private Enrolledstudents enrolledstudents;
	private Studentfees studentfees;
	private Double deductedAmount;
	private Double returnedAmount;
	private Date createdDateTime;
	private Date updatedDateTime;

	public Canceledadmission() {
	}

	public Canceledadmission(Enrolledstudents enrolledstudents, Studentfees studentfees, Double deductedAmount,
			Double returnedAmount, Date createdDateTime, Date updatedDateTime) {
		this.enrolledstudents = enrolledstudents;
		this.studentfees = studentfees;
		this.deductedAmount = deductedAmount;
		this.returnedAmount = returnedAmount;
		this.createdDateTime = createdDateTime;
		this.updatedDateTime = updatedDateTime;
	}

	public Integer getCancellationId() {
		return this.cancellationId;
	}

	public void setCancellationId(Integer cancellationId) {
		this.cancellationId = cancellationId;
	}

	public Enrolledstudents getEnrolledstudents() {
		return this.enrolledstudents;
	}

	public void setEnrolledstudents(Enrolledstudents enrolledstudents) {
		this.enrolledstudents = enrolledstudents;
	}

	public Studentfees getStudentfees() {
		return this.studentfees;
	}

	public void setStudentfees(Studentfees studentfees) {
		this.studentfees = studentfees;
	}

	public Double getDeductedAmount() {
		return this.deductedAmount;
	}

	public void setDeductedAmount(Double deductedAmount) {
		this.deductedAmount = deductedAmount;
	}

	public Double getReturnedAmount() {
		return this.returnedAmount;
	}

	public void setReturnedAmount(Double returnedAmount) {
		this.returnedAmount = returnedAmount;
	}

	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	public Date getUpdatedDateTime() {
		return this.updatedDateTime;
	}

	public void setUpdatedDateTime(Date updatedDateTime) {
		this.updatedDateTime = updatedDateTime;
	}

}
