package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Canceledrequest generated by hbm2java
 */
public class Canceledrequest implements java.io.Serializable {

	private Integer cancellationId;
	private Enrolledstudents enrolledstudents;
	private String reasonForCancellation;
	private Date dateOfCancellation;
	private Date updatedDateTime;

	public Canceledrequest() {
	}

	public Canceledrequest(Enrolledstudents enrolledstudents, String reasonForCancellation, Date dateOfCancellation,
			Date updatedDateTime) {
		this.enrolledstudents = enrolledstudents;
		this.reasonForCancellation = reasonForCancellation;
		this.dateOfCancellation = dateOfCancellation;
		this.updatedDateTime = updatedDateTime;
	}

	public Integer getCancellationId() {
		return this.cancellationId;
	}

	public void setCancellationId(Integer cancellationId) {
		this.cancellationId = cancellationId;
	}

	public Enrolledstudents getEnrolledstudents() {
		return this.enrolledstudents;
	}

	public void setEnrolledstudents(Enrolledstudents enrolledstudents) {
		this.enrolledstudents = enrolledstudents;
	}

	public String getReasonForCancellation() {
		return this.reasonForCancellation;
	}

	public void setReasonForCancellation(String reasonForCancellation) {
		this.reasonForCancellation = reasonForCancellation;
	}

	public Date getDateOfCancellation() {
		return this.dateOfCancellation;
	}

	public void setDateOfCancellation(Date dateOfCancellation) {
		this.dateOfCancellation = dateOfCancellation;
	}

	public Date getUpdatedDateTime() {
		return this.updatedDateTime;
	}

	public void setUpdatedDateTime(Date updatedDateTime) {
		this.updatedDateTime = updatedDateTime;
	}

}
