package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Classdetail generated by hbm2java
 */
public class Classdetail implements java.io.Serializable {

	private Integer classId;
	private String className;
	private Set studentdetails = new HashSet(0);
	private Set notices = new HashSet(0);
	private Set attendances = new HashSet(0);
	private Set timetables = new HashSet(0);

	public Classdetail() {
	}

	public Classdetail(String className, Set studentdetails, Set notices, Set attendances, Set timetables) {
		this.className = className;
		this.studentdetails = studentdetails;
		this.notices = notices;
		this.attendances = attendances;
		this.timetables = timetables;
	}

	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public Set getStudentdetails() {
		return this.studentdetails;
	}

	public void setStudentdetails(Set studentdetails) {
		this.studentdetails = studentdetails;
	}

	public Set getNotices() {
		return this.notices;
	}

	public void setNotices(Set notices) {
		this.notices = notices;
	}

	public Set getAttendances() {
		return this.attendances;
	}

	public void setAttendances(Set attendances) {
		this.attendances = attendances;
	}

	public Set getTimetables() {
		return this.timetables;
	}

	public void setTimetables(Set timetables) {
		this.timetables = timetables;
	}

}
