package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * Coursefees generated by hbm2java
 */
public class Coursefees implements java.io.Serializable {

	private Integer courseFeesId;
	private Semester semester;
	private Course course;
	private Double fees;

	public Coursefees() {
	}

	public Coursefees(Semester semester, Course course, Double fees) {
		this.semester = semester;
		this.course = course;
		this.fees = fees;
	}

	public Integer getCourseFeesId() {
		return this.courseFeesId;
	}

	public void setCourseFeesId(Integer courseFeesId) {
		this.courseFeesId = courseFeesId;
	}

	public Semester getSemester() {
		return this.semester;
	}

	public void setSemester(Semester semester) {
		this.semester = semester;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Double getFees() {
		return this.fees;
	}

	public void setFees(Double fees) {
		this.fees = fees;
	}

}
