package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * Dance generated by hbm2java
 */
public class Dance implements java.io.Serializable {

	private Integer danceId;
	private Enrolledstudents enrolledstudents;
	private String danceType;

	public Dance() {
	}

	public Dance(Enrolledstudents enrolledstudents, String danceType) {
		this.enrolledstudents = enrolledstudents;
		this.danceType = danceType;
	}

	public Integer getDanceId() {
		return this.danceId;
	}

	public void setDanceId(Integer danceId) {
		this.danceId = danceId;
	}

	public Enrolledstudents getEnrolledstudents() {
		return this.enrolledstudents;
	}

	public void setEnrolledstudents(Enrolledstudents enrolledstudents) {
		this.enrolledstudents = enrolledstudents;
	}

	public String getDanceType() {
		return this.danceType;
	}

	public void setDanceType(String danceType) {
		this.danceType = danceType;
	}

}
