package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Diplomadetail generated by hbm2java
 */
public class Diplomadetail implements java.io.Serializable {

	private Integer diplomaDetailId;
	private String collegeName;
	private String collegeCode;
	private Integer zipCode;
	private String city;
	private String university;
	private String enrollmentNumber;
	private Integer passingYear;
	private Double percentage;
	private String diplomaCourse;
	private Set applicationforadmissions = new HashSet(0);

	public Diplomadetail() {
	}

	public Diplomadetail(String collegeName, String collegeCode, Integer zipCode, String city, String university,
			String enrollmentNumber, Integer passingYear, Double percentage, String diplomaCourse,
			Set applicationforadmissions) {
		this.collegeName = collegeName;
		this.collegeCode = collegeCode;
		this.zipCode = zipCode;
		this.city = city;
		this.university = university;
		this.enrollmentNumber = enrollmentNumber;
		this.passingYear = passingYear;
		this.percentage = percentage;
		this.diplomaCourse = diplomaCourse;
		this.applicationforadmissions = applicationforadmissions;
	}

	public Integer getDiplomaDetailId() {
		return this.diplomaDetailId;
	}

	public void setDiplomaDetailId(Integer diplomaDetailId) {
		this.diplomaDetailId = diplomaDetailId;
	}

	public String getCollegeName() {
		return this.collegeName;
	}

	public void setCollegeName(String collegeName) {
		this.collegeName = collegeName;
	}

	public String getCollegeCode() {
		return this.collegeCode;
	}

	public void setCollegeCode(String collegeCode) {
		this.collegeCode = collegeCode;
	}

	public Integer getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(Integer zipCode) {
		this.zipCode = zipCode;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getUniversity() {
		return this.university;
	}

	public void setUniversity(String university) {
		this.university = university;
	}

	public String getEnrollmentNumber() {
		return this.enrollmentNumber;
	}

	public void setEnrollmentNumber(String enrollmentNumber) {
		this.enrollmentNumber = enrollmentNumber;
	}

	public Integer getPassingYear() {
		return this.passingYear;
	}

	public void setPassingYear(Integer passingYear) {
		this.passingYear = passingYear;
	}

	public Double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Double percentage) {
		this.percentage = percentage;
	}

	public String getDiplomaCourse() {
		return this.diplomaCourse;
	}

	public void setDiplomaCourse(String diplomaCourse) {
		this.diplomaCourse = diplomaCourse;
	}

	public Set getApplicationforadmissions() {
		return this.applicationforadmissions;
	}

	public void setApplicationforadmissions(Set applicationforadmissions) {
		this.applicationforadmissions = applicationforadmissions;
	}

}
