package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Events generated by hbm2java
 */
public class Events implements java.io.Serializable {

	private Integer id;
	private String eventName;
	private Date eventDate;
	private Integer deptId;

	public Events() {
	}

	public Events(String eventName, Date eventDate, Integer deptId) {
		this.eventName = eventName;
		this.eventDate = eventDate;
		this.deptId = deptId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

}
