package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Examtimetable generated by hbm2java
 */
public class Examtimetable implements java.io.Serializable {

	private Integer examTimeTableId;
	private Course course;
	private Subjects subjects;
	private Branch branch;
	private String exType;
	private Integer semester;
	private String subCode;
	private String subName;
	private Date exdate;
	private String exTime;
	private Set invigilationdutieses = new HashSet(0);

	public Examtimetable() {
	}

	public Examtimetable(Course course, Subjects subjects, Branch branch, String exType, Integer semester,
			String subCode, String subName, Date exdate, String exTime, Set invigilationdutieses) {
		this.course = course;
		this.subjects = subjects;
		this.branch = branch;
		this.exType = exType;
		this.semester = semester;
		this.subCode = subCode;
		this.subName = subName;
		this.exdate = exdate;
		this.exTime = exTime;
		this.invigilationdutieses = invigilationdutieses;
	}

	public Integer getExamTimeTableId() {
		return this.examTimeTableId;
	}

	public void setExamTimeTableId(Integer examTimeTableId) {
		this.examTimeTableId = examTimeTableId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Subjects getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Subjects subjects) {
		this.subjects = subjects;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public String getExType() {
		return this.exType;
	}

	public void setExType(String exType) {
		this.exType = exType;
	}

	public Integer getSemester() {
		return this.semester;
	}

	public void setSemester(Integer semester) {
		this.semester = semester;
	}

	public String getSubCode() {
		return this.subCode;
	}

	public void setSubCode(String subCode) {
		this.subCode = subCode;
	}

	public String getSubName() {
		return this.subName;
	}

	public void setSubName(String subName) {
		this.subName = subName;
	}

	public Date getExdate() {
		return this.exdate;
	}

	public void setExdate(Date exdate) {
		this.exdate = exdate;
	}

	public String getExTime() {
		return this.exTime;
	}

	public void setExTime(String exTime) {
		this.exTime = exTime;
	}

	public Set getInvigilationdutieses() {
		return this.invigilationdutieses;
	}

	public void setInvigilationdutieses(Set invigilationdutieses) {
		this.invigilationdutieses = invigilationdutieses;
	}

}
