package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Examtransaction generated by hbm2java
 */
public class Examtransaction implements java.io.Serializable {

	private Integer examTransId;
	private Studentdetail studentdetail;
	private Examtype examtype;
	private Teacherdetail teacherdetail;
	private Subject subject;
	private Date examTransDate;
	private Integer examTransThObtMark;
	private Integer examTransThOutOfMark;
	private Integer examTransPractObtMark;
	private Integer examTransPractOutOfMark;
	private Integer examTransTotalObtMark;
	private Integer examTransTotalOutOfMark;
	private Double examTransPercentage;

	public Examtransaction() {
	}

	public Examtransaction(Studentdetail studentdetail, Examtype examtype, Teacherdetail teacherdetail,
			Subject subject, Date examTransDate, Integer examTransThObtMark, Integer examTransThOutOfMark,
			Integer examTransPractObtMark, Integer examTransPractOutOfMark, Integer examTransTotalObtMark,
			Integer examTransTotalOutOfMark, Double examTransPercentage) {
		this.studentdetail = studentdetail;
		this.examtype = examtype;
		this.teacherdetail = teacherdetail;
		this.subject = subject;
		this.examTransDate = examTransDate;
		this.examTransThObtMark = examTransThObtMark;
		this.examTransThOutOfMark = examTransThOutOfMark;
		this.examTransPractObtMark = examTransPractObtMark;
		this.examTransPractOutOfMark = examTransPractOutOfMark;
		this.examTransTotalObtMark = examTransTotalObtMark;
		this.examTransTotalOutOfMark = examTransTotalOutOfMark;
		this.examTransPercentage = examTransPercentage;
	}

	public Integer getExamTransId() {
		return this.examTransId;
	}

	public void setExamTransId(Integer examTransId) {
		this.examTransId = examTransId;
	}

	public Studentdetail getStudentdetail() {
		return this.studentdetail;
	}

	public void setStudentdetail(Studentdetail studentdetail) {
		this.studentdetail = studentdetail;
	}

	public Examtype getExamtype() {
		return this.examtype;
	}

	public void setExamtype(Examtype examtype) {
		this.examtype = examtype;
	}

	public Teacherdetail getTeacherdetail() {
		return this.teacherdetail;
	}

	public void setTeacherdetail(Teacherdetail teacherdetail) {
		this.teacherdetail = teacherdetail;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public Date getExamTransDate() {
		return this.examTransDate;
	}

	public void setExamTransDate(Date examTransDate) {
		this.examTransDate = examTransDate;
	}

	public Integer getExamTransThObtMark() {
		return this.examTransThObtMark;
	}

	public void setExamTransThObtMark(Integer examTransThObtMark) {
		this.examTransThObtMark = examTransThObtMark;
	}

	public Integer getExamTransThOutOfMark() {
		return this.examTransThOutOfMark;
	}

	public void setExamTransThOutOfMark(Integer examTransThOutOfMark) {
		this.examTransThOutOfMark = examTransThOutOfMark;
	}

	public Integer getExamTransPractObtMark() {
		return this.examTransPractObtMark;
	}

	public void setExamTransPractObtMark(Integer examTransPractObtMark) {
		this.examTransPractObtMark = examTransPractObtMark;
	}

	public Integer getExamTransPractOutOfMark() {
		return this.examTransPractOutOfMark;
	}

	public void setExamTransPractOutOfMark(Integer examTransPractOutOfMark) {
		this.examTransPractOutOfMark = examTransPractOutOfMark;
	}

	public Integer getExamTransTotalObtMark() {
		return this.examTransTotalObtMark;
	}

	public void setExamTransTotalObtMark(Integer examTransTotalObtMark) {
		this.examTransTotalObtMark = examTransTotalObtMark;
	}

	public Integer getExamTransTotalOutOfMark() {
		return this.examTransTotalOutOfMark;
	}

	public void setExamTransTotalOutOfMark(Integer examTransTotalOutOfMark) {
		this.examTransTotalOutOfMark = examTransTotalOutOfMark;
	}

	public Double getExamTransPercentage() {
		return this.examTransPercentage;
	}

	public void setExamTransPercentage(Double examTransPercentage) {
		this.examTransPercentage = examTransPercentage;
	}

}
