package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Genderforhostelroom generated by hbm2java
 */
public class Genderforhostelroom implements java.io.Serializable {

	private Integer genderId;
	private String gender;
	private Set studentrooms = new HashSet(0);
	private Set visitortrooms = new HashSet(0);
	private Set teacherrooms = new HashSet(0);

	public Genderforhostelroom() {
	}

	public Genderforhostelroom(String gender, Set studentrooms, Set visitortrooms, Set teacherrooms) {
		this.gender = gender;
		this.studentrooms = studentrooms;
		this.visitortrooms = visitortrooms;
		this.teacherrooms = teacherrooms;
	}

	public Integer getGenderId() {
		return this.genderId;
	}

	public void setGenderId(Integer genderId) {
		this.genderId = genderId;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Set getStudentrooms() {
		return this.studentrooms;
	}

	public void setStudentrooms(Set studentrooms) {
		this.studentrooms = studentrooms;
	}

	public Set getVisitortrooms() {
		return this.visitortrooms;
	}

	public void setVisitortrooms(Set visitortrooms) {
		this.visitortrooms = visitortrooms;
	}

	public Set getTeacherrooms() {
		return this.teacherrooms;
	}

	public void setTeacherrooms(Set teacherrooms) {
		this.teacherrooms = teacherrooms;
	}

}
