package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Holidays generated by hbm2java
 */
public class Holidays implements java.io.Serializable {

	private Integer id;
	private String holidayName;
	private Date holidayDate;

	public Holidays() {
	}

	public Holidays(String holidayName, Date holidayDate) {
		this.holidayName = holidayName;
		this.holidayDate = holidayDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getHolidayName() {
		return this.holidayName;
	}

	public void setHolidayName(String holidayName) {
		this.holidayName = holidayName;
	}

	public Date getHolidayDate() {
		return this.holidayDate;
	}

	public void setHolidayDate(Date holidayDate) {
		this.holidayDate = holidayDate;
	}

}
