package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * Hostelfees generated by hbm2java
 */
public class Hostelfees implements java.io.Serializable {

	private Integer hostelFeesId;
	private Hostelregistration hostelregistration;
	private Double totalFees;
	private Double paidFees;
	private Double remainingFees;

	public Hostelfees() {
	}

	public Hostelfees(Hostelregistration hostelregistration, Double totalFees, Double paidFees, Double remainingFees) {
		this.hostelregistration = hostelregistration;
		this.totalFees = totalFees;
		this.paidFees = paidFees;
		this.remainingFees = remainingFees;
	}

	public Integer getHostelFeesId() {
		return this.hostelFeesId;
	}

	public void setHostelFeesId(Integer hostelFeesId) {
		this.hostelFeesId = hostelFeesId;
	}

	public Hostelregistration getHostelregistration() {
		return this.hostelregistration;
	}

	public void setHostelregistration(Hostelregistration hostelregistration) {
		this.hostelregistration = hostelregistration;
	}

	public Double getTotalFees() {
		return this.totalFees;
	}

	public void setTotalFees(Double totalFees) {
		this.totalFees = totalFees;
	}

	public Double getPaidFees() {
		return this.paidFees;
	}

	public void setPaidFees(Double paidFees) {
		this.paidFees = paidFees;
	}

	public Double getRemainingFees() {
		return this.remainingFees;
	}

	public void setRemainingFees(Double remainingFees) {
		this.remainingFees = remainingFees;
	}

}
