package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Hostelroomsallot generated by hbm2java
 */
public class Hostelroomsallot implements java.io.Serializable {

	private Integer hostelRoomId;
	private Visitortroom visitortroom;
	private Studentroom studentroom;
	private Teacherroom teacherroom;
	private String hostelRoomNumber;
	private Integer hostelRoomMembers;
	private Set hostelregistrations = new HashSet(0);

	public Hostelroomsallot() {
	}

	public Hostelroomsallot(Visitortroom visitortroom, Studentroom studentroom, Teacherroom teacherroom,
			String hostelRoomNumber, Integer hostelRoomMembers, Set hostelregistrations) {
		this.visitortroom = visitortroom;
		this.studentroom = studentroom;
		this.teacherroom = teacherroom;
		this.hostelRoomNumber = hostelRoomNumber;
		this.hostelRoomMembers = hostelRoomMembers;
		this.hostelregistrations = hostelregistrations;
	}

	public Integer getHostelRoomId() {
		return this.hostelRoomId;
	}

	public void setHostelRoomId(Integer hostelRoomId) {
		this.hostelRoomId = hostelRoomId;
	}

	public Visitortroom getVisitortroom() {
		return this.visitortroom;
	}

	public void setVisitortroom(Visitortroom visitortroom) {
		this.visitortroom = visitortroom;
	}

	public Studentroom getStudentroom() {
		return this.studentroom;
	}

	public void setStudentroom(Studentroom studentroom) {
		this.studentroom = studentroom;
	}

	public Teacherroom getTeacherroom() {
		return this.teacherroom;
	}

	public void setTeacherroom(Teacherroom teacherroom) {
		this.teacherroom = teacherroom;
	}

	public String getHostelRoomNumber() {
		return this.hostelRoomNumber;
	}

	public void setHostelRoomNumber(String hostelRoomNumber) {
		this.hostelRoomNumber = hostelRoomNumber;
	}

	public Integer getHostelRoomMembers() {
		return this.hostelRoomMembers;
	}

	public void setHostelRoomMembers(Integer hostelRoomMembers) {
		this.hostelRoomMembers = hostelRoomMembers;
	}

	public Set getHostelregistrations() {
		return this.hostelregistrations;
	}

	public void setHostelregistrations(Set hostelregistrations) {
		this.hostelregistrations = hostelregistrations;
	}

}
