package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hostelregistration generated by hbm2java
 */
public class Hostelregistration implements java.io.Serializable {

	private Integer hregId;
	private Hostelroomsallot hostelroomsallot;
	private Teacher teacher;
	private Applicationforadmission applicationforadmission;
	private Hostelmess hostelmess;
	private Date formSubmitDate;
	private Date adminAllotDate;
	private Integer status;
	private String hlocalAddress;
	private String hroomType;
	private String messFoodType;
	private String rejectRason;
	private Integer acceptStatus;
	private Set hostelattendences = new HashSet(0);
	private Set hostelfeeses = new HashSet(0);
	private Set hostelmesses = new HashSet(0);
	private Set hostelleaveapplications = new HashSet(0);

	public Hostelregistration() {
	}

	public Hostelregistration(Hostelroomsallot hostelroomsallot, Teacher teacher,
			Applicationforadmission applicationforadmission, Hostelmess hostelmess, Date formSubmitDate,
			Date adminAllotDate, Integer status, String hlocalAddress, String hroomType, String messFoodType,
			String rejectRason, Integer acceptStatus, Set hostelattendences, Set hostelfeeses, Set hostelmesses,
			Set hostelleaveapplications) {
		this.hostelroomsallot = hostelroomsallot;
		this.teacher = teacher;
		this.applicationforadmission = applicationforadmission;
		this.hostelmess = hostelmess;
		this.formSubmitDate = formSubmitDate;
		this.adminAllotDate = adminAllotDate;
		this.status = status;
		this.hlocalAddress = hlocalAddress;
		this.hroomType = hroomType;
		this.messFoodType = messFoodType;
		this.rejectRason = rejectRason;
		this.acceptStatus = acceptStatus;
		this.hostelattendences = hostelattendences;
		this.hostelfeeses = hostelfeeses;
		this.hostelmesses = hostelmesses;
		this.hostelleaveapplications = hostelleaveapplications;
	}

	public Integer getHregId() {
		return this.hregId;
	}

	public void setHregId(Integer hregId) {
		this.hregId = hregId;
	}

	public Hostelroomsallot getHostelroomsallot() {
		return this.hostelroomsallot;
	}

	public void setHostelroomsallot(Hostelroomsallot hostelroomsallot) {
		this.hostelroomsallot = hostelroomsallot;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Applicationforadmission getApplicationforadmission() {
		return this.applicationforadmission;
	}

	public void setApplicationforadmission(Applicationforadmission applicationforadmission) {
		this.applicationforadmission = applicationforadmission;
	}

	public Hostelmess getHostelmess() {
		return this.hostelmess;
	}

	public void setHostelmess(Hostelmess hostelmess) {
		this.hostelmess = hostelmess;
	}

	public Date getFormSubmitDate() {
		return this.formSubmitDate;
	}

	public void setFormSubmitDate(Date formSubmitDate) {
		this.formSubmitDate = formSubmitDate;
	}

	public Date getAdminAllotDate() {
		return this.adminAllotDate;
	}

	public void setAdminAllotDate(Date adminAllotDate) {
		this.adminAllotDate = adminAllotDate;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getHlocalAddress() {
		return this.hlocalAddress;
	}

	public void setHlocalAddress(String hlocalAddress) {
		this.hlocalAddress = hlocalAddress;
	}

	public String getHroomType() {
		return this.hroomType;
	}

	public void setHroomType(String hroomType) {
		this.hroomType = hroomType;
	}

	public String getMessFoodType() {
		return this.messFoodType;
	}

	public void setMessFoodType(String messFoodType) {
		this.messFoodType = messFoodType;
	}

	public String getRejectRason() {
		return this.rejectRason;
	}

	public void setRejectRason(String rejectRason) {
		this.rejectRason = rejectRason;
	}

	public Integer getAcceptStatus() {
		return this.acceptStatus;
	}

	public void setAcceptStatus(Integer acceptStatus) {
		this.acceptStatus = acceptStatus;
	}

	public Set getHostelattendences() {
		return this.hostelattendences;
	}

	public void setHostelattendences(Set hostelattendences) {
		this.hostelattendences = hostelattendences;
	}

	public Set getHostelfeeses() {
		return this.hostelfeeses;
	}

	public void setHostelfeeses(Set hostelfeeses) {
		this.hostelfeeses = hostelfeeses;
	}

	public Set getHostelmesses() {
		return this.hostelmesses;
	}

	public void setHostelmesses(Set hostelmesses) {
		this.hostelmesses = hostelmesses;
	}

	public Set getHostelleaveapplications() {
		return this.hostelleaveapplications;
	}

	public void setHostelleaveapplications(Set hostelleaveapplications) {
		this.hostelleaveapplications = hostelleaveapplications;
	}

}
