package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Hostelmessfoodtype generated by hbm2java
 */
public class Hostelmessfoodtype implements java.io.Serializable {

	private Integer foodTypeId;
	private String foodTypeName;
	private Set hostelmesses = new HashSet(0);

	public Hostelmessfoodtype() {
	}

	public Hostelmessfoodtype(String foodTypeName, Set hostelmesses) {
		this.foodTypeName = foodTypeName;
		this.hostelmesses = hostelmesses;
	}

	public Integer getFoodTypeId() {
		return this.foodTypeId;
	}

	public void setFoodTypeId(Integer foodTypeId) {
		this.foodTypeId = foodTypeId;
	}

	public String getFoodTypeName() {
		return this.foodTypeName;
	}

	public void setFoodTypeName(String foodTypeName) {
		this.foodTypeName = foodTypeName;
	}

	public Set getHostelmesses() {
		return this.hostelmesses;
	}

	public void setHostelmesses(Set hostelmesses) {
		this.hostelmesses = hostelmesses;
	}

}
