package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Hostelleaveapplication generated by hbm2java
 */
public class Hostelleaveapplication implements java.io.Serializable {

	private Integer leaveId;
	private Hostelregistration hostelregistration;
	private String other;
	private Integer numberOfDays;
	private Date currentDate;
	private Date returnDate;
	private String causeOfLeave;
	private String leaveStatus;

	public Hostelleaveapplication() {
	}

	public Hostelleaveapplication(Hostelregistration hostelregistration, String other, Integer numberOfDays,
			Date currentDate, Date returnDate, String causeOfLeave, String leaveStatus) {
		this.hostelregistration = hostelregistration;
		this.other = other;
		this.numberOfDays = numberOfDays;
		this.currentDate = currentDate;
		this.returnDate = returnDate;
		this.causeOfLeave = causeOfLeave;
		this.leaveStatus = leaveStatus;
	}

	public Integer getLeaveId() {
		return this.leaveId;
	}

	public void setLeaveId(Integer leaveId) {
		this.leaveId = leaveId;
	}

	public Hostelregistration getHostelregistration() {
		return this.hostelregistration;
	}

	public void setHostelregistration(Hostelregistration hostelregistration) {
		this.hostelregistration = hostelregistration;
	}

	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	public Integer getNumberOfDays() {
		return this.numberOfDays;
	}

	public void setNumberOfDays(Integer numberOfDays) {
		this.numberOfDays = numberOfDays;
	}

	public Date getCurrentDate() {
		return this.currentDate;
	}

	public void setCurrentDate(Date currentDate) {
		this.currentDate = currentDate;
	}

	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	public String getCauseOfLeave() {
		return this.causeOfLeave;
	}

	public void setCauseOfLeave(String causeOfLeave) {
		this.causeOfLeave = causeOfLeave;
	}

	public String getLeaveStatus() {
		return this.leaveStatus;
	}

	public void setLeaveStatus(String leaveStatus) {
		this.leaveStatus = leaveStatus;
	}

}
