package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Hostelmess generated by hbm2java
 */
public class Hostelmess implements java.io.Serializable {

	private Integer hmessId;
	private Hostelmessfoodtype hostelmessfoodtype;
	private Hostelregistration hostelregistration;
	private Integer hmessTeacherId;
	private Double hmessFeesPaid;
	private Double hmessFeesRemain;
	private Integer hmessMonthLeaveRemain;
	private Double hmessOtherBills;
	private Integer hmessAttendenceId;
	private Set messattendences = new HashSet(0);
	private Set hostelregistrations = new HashSet(0);

	public Hostelmess() {
	}

	public Hostelmess(Hostelmessfoodtype hostelmessfoodtype, Hostelregistration hostelregistration,
			Integer hmessTeacherId, Double hmessFeesPaid, Double hmessFeesRemain, Integer hmessMonthLeaveRemain,
			Double hmessOtherBills, Integer hmessAttendenceId, Set messattendences, Set hostelregistrations) {
		this.hostelmessfoodtype = hostelmessfoodtype;
		this.hostelregistration = hostelregistration;
		this.hmessTeacherId = hmessTeacherId;
		this.hmessFeesPaid = hmessFeesPaid;
		this.hmessFeesRemain = hmessFeesRemain;
		this.hmessMonthLeaveRemain = hmessMonthLeaveRemain;
		this.hmessOtherBills = hmessOtherBills;
		this.hmessAttendenceId = hmessAttendenceId;
		this.messattendences = messattendences;
		this.hostelregistrations = hostelregistrations;
	}

	public Integer getHmessId() {
		return this.hmessId;
	}

	public void setHmessId(Integer hmessId) {
		this.hmessId = hmessId;
	}

	public Hostelmessfoodtype getHostelmessfoodtype() {
		return this.hostelmessfoodtype;
	}

	public void setHostelmessfoodtype(Hostelmessfoodtype hostelmessfoodtype) {
		this.hostelmessfoodtype = hostelmessfoodtype;
	}

	public Hostelregistration getHostelregistration() {
		return this.hostelregistration;
	}

	public void setHostelregistration(Hostelregistration hostelregistration) {
		this.hostelregistration = hostelregistration;
	}

	public Integer getHmessTeacherId() {
		return this.hmessTeacherId;
	}

	public void setHmessTeacherId(Integer hmessTeacherId) {
		this.hmessTeacherId = hmessTeacherId;
	}

	public Double getHmessFeesPaid() {
		return this.hmessFeesPaid;
	}

	public void setHmessFeesPaid(Double hmessFeesPaid) {
		this.hmessFeesPaid = hmessFeesPaid;
	}

	public Double getHmessFeesRemain() {
		return this.hmessFeesRemain;
	}

	public void setHmessFeesRemain(Double hmessFeesRemain) {
		this.hmessFeesRemain = hmessFeesRemain;
	}

	public Integer getHmessMonthLeaveRemain() {
		return this.hmessMonthLeaveRemain;
	}

	public void setHmessMonthLeaveRemain(Integer hmessMonthLeaveRemain) {
		this.hmessMonthLeaveRemain = hmessMonthLeaveRemain;
	}

	public Double getHmessOtherBills() {
		return this.hmessOtherBills;
	}

	public void setHmessOtherBills(Double hmessOtherBills) {
		this.hmessOtherBills = hmessOtherBills;
	}

	public Integer getHmessAttendenceId() {
		return this.hmessAttendenceId;
	}

	public void setHmessAttendenceId(Integer hmessAttendenceId) {
		this.hmessAttendenceId = hmessAttendenceId;
	}

	public Set getMessattendences() {
		return this.messattendences;
	}

	public void setMessattendences(Set messattendences) {
		this.messattendences = messattendences;
	}

	public Set getHostelregistrations() {
		return this.hostelregistrations;
	}

	public void setHostelregistrations(Set hostelregistrations) {
		this.hostelregistrations = hostelregistrations;
	}

}
