package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Hostelattendence generated by hbm2java
 */
public class Hostelattendence implements java.io.Serializable {

	private Integer hattendenceId;
	private Hostelregistration hostelregistration;
	private Attendencetype attendencetype;
	private Date dateAndTime;

	public Hostelattendence() {
	}

	public Hostelattendence(Hostelregistration hostelregistration, Attendencetype attendencetype, Date dateAndTime) {
		this.hostelregistration = hostelregistration;
		this.attendencetype = attendencetype;
		this.dateAndTime = dateAndTime;
	}

	public Integer getHattendenceId() {
		return this.hattendenceId;
	}

	public void setHattendenceId(Integer hattendenceId) {
		this.hattendenceId = hattendenceId;
	}

	public Hostelregistration getHostelregistration() {
		return this.hostelregistration;
	}

	public void setHostelregistration(Hostelregistration hostelregistration) {
		this.hostelregistration = hostelregistration;
	}

	public Attendencetype getAttendencetype() {
		return this.attendencetype;
	}

	public void setAttendencetype(Attendencetype attendencetype) {
		this.attendencetype = attendencetype;
	}

	public Date getDateAndTime() {
		return this.dateAndTime;
	}

	public void setDateAndTime(Date dateAndTime) {
		this.dateAndTime = dateAndTime;
	}

}
