package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Inventoryrequest generated by hbm2java
 */
public class Inventoryrequest implements java.io.Serializable {

	private Integer inventoryRequestId;
	private Teacherdetail teacherdetail;
	private Integer adminId;
	private Integer quantity;
	private String inventoryName;
	private Date inventoryRequestDateTime;
	private String inventoryStatus;
	private Set adminaddinventories = new HashSet(0);

	public Inventoryrequest() {
	}

	public Inventoryrequest(Teacherdetail teacherdetail, Integer adminId, Integer quantity, String inventoryName,
			Date inventoryRequestDateTime, String inventoryStatus, Set adminaddinventories) {
		this.teacherdetail = teacherdetail;
		this.adminId = adminId;
		this.quantity = quantity;
		this.inventoryName = inventoryName;
		this.inventoryRequestDateTime = inventoryRequestDateTime;
		this.inventoryStatus = inventoryStatus;
		this.adminaddinventories = adminaddinventories;
	}

	public Integer getInventoryRequestId() {
		return this.inventoryRequestId;
	}

	public void setInventoryRequestId(Integer inventoryRequestId) {
		this.inventoryRequestId = inventoryRequestId;
	}

	public Teacherdetail getTeacherdetail() {
		return this.teacherdetail;
	}

	public void setTeacherdetail(Teacherdetail teacherdetail) {
		this.teacherdetail = teacherdetail;
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public String getInventoryName() {
		return this.inventoryName;
	}

	public void setInventoryName(String inventoryName) {
		this.inventoryName = inventoryName;
	}

	public Date getInventoryRequestDateTime() {
		return this.inventoryRequestDateTime;
	}

	public void setInventoryRequestDateTime(Date inventoryRequestDateTime) {
		this.inventoryRequestDateTime = inventoryRequestDateTime;
	}

	public String getInventoryStatus() {
		return this.inventoryStatus;
	}

	public void setInventoryStatus(String inventoryStatus) {
		this.inventoryStatus = inventoryStatus;
	}

	public Set getAdminaddinventories() {
		return this.adminaddinventories;
	}

	public void setAdminaddinventories(Set adminaddinventories) {
		this.adminaddinventories = adminaddinventories;
	}

}
