package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * Invigilationduties generated by hbm2java
 */
public class Invigilationduties implements java.io.Serializable {

	private Integer dutiesId;
	private Examtimetable examtimetable;
	private Teacherdetail teacherdetail;
	private Integer roomNo;
	private String building;

	public Invigilationduties() {
	}

	public Invigilationduties(Examtimetable examtimetable, Teacherdetail teacherdetail, Integer roomNo, String building) {
		this.examtimetable = examtimetable;
		this.teacherdetail = teacherdetail;
		this.roomNo = roomNo;
		this.building = building;
	}

	public Integer getDutiesId() {
		return this.dutiesId;
	}

	public void setDutiesId(Integer dutiesId) {
		this.dutiesId = dutiesId;
	}

	public Examtimetable getExamtimetable() {
		return this.examtimetable;
	}

	public void setExamtimetable(Examtimetable examtimetable) {
		this.examtimetable = examtimetable;
	}

	public Teacherdetail getTeacherdetail() {
		return this.teacherdetail;
	}

	public void setTeacherdetail(Teacherdetail teacherdetail) {
		this.teacherdetail = teacherdetail;
	}

	public Integer getRoomNo() {
		return this.roomNo;
	}

	public void setRoomNo(Integer roomNo) {
		this.roomNo = roomNo;
	}

	public String getBuilding() {
		return this.building;
	}

	public void setBuilding(String building) {
		this.building = building;
	}

}
