package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * Loginstudentteacher generated by hbm2java
 */
public class Loginstudentteacher implements java.io.Serializable {

	private Integer id;
	private Enrolledstudents enrolledstudents;
	private Teacherdetail teacherdetail;
	private String password;
	private String adminEmail;

	public Loginstudentteacher() {
	}

	public Loginstudentteacher(Enrolledstudents enrolledstudents, Teacherdetail teacherdetail, String password,
			String adminEmail) {
		this.enrolledstudents = enrolledstudents;
		this.teacherdetail = teacherdetail;
		this.password = password;
		this.adminEmail = adminEmail;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Enrolledstudents getEnrolledstudents() {
		return this.enrolledstudents;
	}

	public void setEnrolledstudents(Enrolledstudents enrolledstudents) {
		this.enrolledstudents = enrolledstudents;
	}

	public Teacherdetail getTeacherdetail() {
		return this.teacherdetail;
	}

	public void setTeacherdetail(Teacherdetail teacherdetail) {
		this.teacherdetail = teacherdetail;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAdminEmail() {
		return this.adminEmail;
	}

	public void setAdminEmail(String adminEmail) {
		this.adminEmail = adminEmail;
	}

}
