package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * Music generated by hbm2java
 */
public class Music implements java.io.Serializable {

	private Integer musicId;
	private Enrolledstudents enrolledstudents;
	private String instruments;

	public Music() {
	}

	public Music(Enrolledstudents enrolledstudents, String instruments) {
		this.enrolledstudents = enrolledstudents;
		this.instruments = instruments;
	}

	public Integer getMusicId() {
		return this.musicId;
	}

	public void setMusicId(Integer musicId) {
		this.musicId = musicId;
	}

	public Enrolledstudents getEnrolledstudents() {
		return this.enrolledstudents;
	}

	public void setEnrolledstudents(Enrolledstudents enrolledstudents) {
		this.enrolledstudents = enrolledstudents;
	}

	public String getInstruments() {
		return this.instruments;
	}

	public void setInstruments(String instruments) {
		this.instruments = instruments;
	}

}
