package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Registration implements java.io.Serializable {

	private Integer regId;
	private String regFirstName;
	private String regMiddleName;
	private String regLastName;
	private String regGender;
	private Date regDob;
	private String regPrimaryEmailId;
	private Long regPhoneNumber;
	private String regPassword;
	private String regConfirmPassword;
	private String regSecurityQuestion;
	private String regAnswer;
	private Set applicationforadmissions = new HashSet(0);

	public Registration() {
	}

	public Registration(String regFirstName, String regMiddleName, String regLastName, String regGender, Date regDob,
			String regPrimaryEmailId, Long regPhoneNumber, String regPassword, String regConfirmPassword,
			String regSecurityQuestion, String regAnswer, Set applicationforadmissions) {
		this.regFirstName = regFirstName;
		this.regMiddleName = regMiddleName;
		this.regLastName = regLastName;
		this.regGender = regGender;
		this.regDob = regDob;
		this.regPrimaryEmailId = regPrimaryEmailId;
		this.regPhoneNumber = regPhoneNumber;
		this.regPassword = regPassword;
		this.regConfirmPassword = regConfirmPassword;
		this.regSecurityQuestion = regSecurityQuestion;
		this.regAnswer = regAnswer;
		this.applicationforadmissions = applicationforadmissions;
	}

	public Integer getRegId() {
		return this.regId;
	}

	public void setRegId(Integer regId) {
		this.regId = regId;
	}

	public String getRegFirstName() {
		return this.regFirstName;
	}

	public void setRegFirstName(String regFirstName) {
		this.regFirstName = regFirstName;
	}

	public String getRegMiddleName() {
		return this.regMiddleName;
	}

	public void setRegMiddleName(String regMiddleName) {
		this.regMiddleName = regMiddleName;
	}

	public String getRegLastName() {
		return this.regLastName;
	}

	public void setRegLastName(String regLastName) {
		this.regLastName = regLastName;
	}

	public String getRegGender() {
		return this.regGender;
	}

	public void setRegGender(String regGender) {
		this.regGender = regGender;
	}

	public Date getRegDob() {
		return this.regDob;
	}

	public void setRegDob(Date regDob) {
		this.regDob = regDob;
	}

	public String getRegPrimaryEmailId() {
		return this.regPrimaryEmailId;
	}

	public void setRegPrimaryEmailId(String regPrimaryEmailId) {
		this.regPrimaryEmailId = regPrimaryEmailId;
	}

	public Long getRegPhoneNumber() {
		return this.regPhoneNumber;
	}

	public void setRegPhoneNumber(Long regPhoneNumber) {
		this.regPhoneNumber = regPhoneNumber;
	}

	public String getRegPassword() {
		return this.regPassword;
	}

	public void setRegPassword(String regPassword) {
		this.regPassword = regPassword;
	}

	public String getRegConfirmPassword() {
		return this.regConfirmPassword;
	}

	public void setRegConfirmPassword(String regConfirmPassword) {
		this.regConfirmPassword = regConfirmPassword;
	}

	public String getRegSecurityQuestion() {
		return this.regSecurityQuestion;
	}

	public void setRegSecurityQuestion(String regSecurityQuestion) {
		this.regSecurityQuestion = regSecurityQuestion;
	}

	public String getRegAnswer() {
		return this.regAnswer;
	}

	public void setRegAnswer(String regAnswer) {
		this.regAnswer = regAnswer;
	}

	public Set getApplicationforadmissions() {
		return this.applicationforadmissions;
	}

	public void setApplicationforadmissions(Set applicationforadmissions) {
		this.applicationforadmissions = applicationforadmissions;
	}

}
