package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Sscdetail generated by hbm2java
 */
public class Sscdetail implements java.io.Serializable {

	private Integer sscdetailId;
	private String sscschoolName;
	private String city;
	private String sscseatNumber;
	private Integer passingYear;
	private Double percentage;
	private String board;
	private Set applicationforadmissions = new HashSet(0);

	public Sscdetail() {
	}

	public Sscdetail(String sscschoolName, String city, String sscseatNumber, Integer passingYear, Double percentage,
			String board, Set applicationforadmissions) {
		this.sscschoolName = sscschoolName;
		this.city = city;
		this.sscseatNumber = sscseatNumber;
		this.passingYear = passingYear;
		this.percentage = percentage;
		this.board = board;
		this.applicationforadmissions = applicationforadmissions;
	}

	public Integer getSscdetailId() {
		return this.sscdetailId;
	}

	public void setSscdetailId(Integer sscdetailId) {
		this.sscdetailId = sscdetailId;
	}

	public String getSscschoolName() {
		return this.sscschoolName;
	}

	public void setSscschoolName(String sscschoolName) {
		this.sscschoolName = sscschoolName;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getSscseatNumber() {
		return this.sscseatNumber;
	}

	public void setSscseatNumber(String sscseatNumber) {
		this.sscseatNumber = sscseatNumber;
	}

	public Integer getPassingYear() {
		return this.passingYear;
	}

	public void setPassingYear(Integer passingYear) {
		this.passingYear = passingYear;
	}

	public Double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Double percentage) {
		this.percentage = percentage;
	}

	public String getBoard() {
		return this.board;
	}

	public void setBoard(String board) {
		this.board = board;
	}

	public Set getApplicationforadmissions() {
		return this.applicationforadmissions;
	}

	public void setApplicationforadmissions(Set applicationforadmissions) {
		this.applicationforadmissions = applicationforadmissions;
	}

}
