package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Studenttransportfees generated by hbm2java
 */
public class Studenttransportfees implements java.io.Serializable {

	private Integer transportFeesPaymentId;
	private Enrolledstudents enrolledstudents;
	private Date paymentDate;
	private Double paidFees;

	public Studenttransportfees() {
	}

	public Studenttransportfees(Enrolledstudents enrolledstudents, Date paymentDate, Double paidFees) {
		this.enrolledstudents = enrolledstudents;
		this.paymentDate = paymentDate;
		this.paidFees = paidFees;
	}

	public Integer getTransportFeesPaymentId() {
		return this.transportFeesPaymentId;
	}

	public void setTransportFeesPaymentId(Integer transportFeesPaymentId) {
		this.transportFeesPaymentId = transportFeesPaymentId;
	}

	public Enrolledstudents getEnrolledstudents() {
		return this.enrolledstudents;
	}

	public void setEnrolledstudents(Enrolledstudents enrolledstudents) {
		this.enrolledstudents = enrolledstudents;
	}

	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	public Double getPaidFees() {
		return this.paidFees;
	}

	public void setPaidFees(Double paidFees) {
		this.paidFees = paidFees;
	}

}
