package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Studentattendance generated by hbm2java
 */
public class Studentattendance implements java.io.Serializable {

	private Integer attendId;
	private Attendencetype attendencetype;
	private Enrolledstudents enrolledstudents;
	private Date attendTimeDateAndTime;

	public Studentattendance() {
	}

	public Studentattendance(Attendencetype attendencetype, Enrolledstudents enrolledstudents,
			Date attendTimeDateAndTime) {
		this.attendencetype = attendencetype;
		this.enrolledstudents = enrolledstudents;
		this.attendTimeDateAndTime = attendTimeDateAndTime;
	}

	public Integer getAttendId() {
		return this.attendId;
	}

	public void setAttendId(Integer attendId) {
		this.attendId = attendId;
	}

	public Attendencetype getAttendencetype() {
		return this.attendencetype;
	}

	public void setAttendencetype(Attendencetype attendencetype) {
		this.attendencetype = attendencetype;
	}

	public Enrolledstudents getEnrolledstudents() {
		return this.enrolledstudents;
	}

	public void setEnrolledstudents(Enrolledstudents enrolledstudents) {
		this.enrolledstudents = enrolledstudents;
	}

	public Date getAttendTimeDateAndTime() {
		return this.attendTimeDateAndTime;
	}

	public void setAttendTimeDateAndTime(Date attendTimeDateAndTime) {
		this.attendTimeDateAndTime = attendTimeDateAndTime;
	}

}
