package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Studentdetail generated by hbm2java
 */
public class Studentdetail implements java.io.Serializable {

	private Integer studId;
	private Yeardetail yeardetail;
	private Classdetail classdetail;
	private Division division;
	private String studEnrollmentN;
	private String studName;
	private Set examtransactions = new HashSet(0);
	private Set attendances = new HashSet(0);
	private Set timetables = new HashSet(0);

	public Studentdetail() {
	}

	public Studentdetail(Yeardetail yeardetail, Classdetail classdetail, Division division, String studEnrollmentN,
			String studName, Set examtransactions, Set attendances, Set timetables) {
		this.yeardetail = yeardetail;
		this.classdetail = classdetail;
		this.division = division;
		this.studEnrollmentN = studEnrollmentN;
		this.studName = studName;
		this.examtransactions = examtransactions;
		this.attendances = attendances;
		this.timetables = timetables;
	}

	public Integer getStudId() {
		return this.studId;
	}

	public void setStudId(Integer studId) {
		this.studId = studId;
	}

	public Yeardetail getYeardetail() {
		return this.yeardetail;
	}

	public void setYeardetail(Yeardetail yeardetail) {
		this.yeardetail = yeardetail;
	}

	public Classdetail getClassdetail() {
		return this.classdetail;
	}

	public void setClassdetail(Classdetail classdetail) {
		this.classdetail = classdetail;
	}

	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	public String getStudEnrollmentN() {
		return this.studEnrollmentN;
	}

	public void setStudEnrollmentN(String studEnrollmentN) {
		this.studEnrollmentN = studEnrollmentN;
	}

	public String getStudName() {
		return this.studName;
	}

	public void setStudName(String studName) {
		this.studName = studName;
	}

	public Set getExamtransactions() {
		return this.examtransactions;
	}

	public void setExamtransactions(Set examtransactions) {
		this.examtransactions = examtransactions;
	}

	public Set getAttendances() {
		return this.attendances;
	}

	public void setAttendances(Set attendances) {
		this.attendances = attendances;
	}

	public Set getTimetables() {
		return this.timetables;
	}

	public void setTimetables(Set timetables) {
		this.timetables = timetables;
	}

}
