package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Studentadmitnfees generated by hbm2java
 */
public class Studentadmitnfees implements java.io.Serializable {

	private Integer feesPaymentId;
	private Semester semester;
	private Course course;
	private Applicationforadmission applicationforadmission;
	private String paymentMode;
	private Date paymentDate;
	private Double totalFees;
	private Double paidFees;
	private Double remainingFees;
	private Set feestransactions = new HashSet(0);

	public Studentadmitnfees() {
	}

	public Studentadmitnfees(Semester semester, Course course, Applicationforadmission applicationforadmission,
			String paymentMode, Date paymentDate, Double totalFees, Double paidFees, Double remainingFees,
			Set feestransactions) {
		this.semester = semester;
		this.course = course;
		this.applicationforadmission = applicationforadmission;
		this.paymentMode = paymentMode;
		this.paymentDate = paymentDate;
		this.totalFees = totalFees;
		this.paidFees = paidFees;
		this.remainingFees = remainingFees;
		this.feestransactions = feestransactions;
	}

	public Integer getFeesPaymentId() {
		return this.feesPaymentId;
	}

	public void setFeesPaymentId(Integer feesPaymentId) {
		this.feesPaymentId = feesPaymentId;
	}

	public Semester getSemester() {
		return this.semester;
	}

	public void setSemester(Semester semester) {
		this.semester = semester;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Applicationforadmission getApplicationforadmission() {
		return this.applicationforadmission;
	}

	public void setApplicationforadmission(Applicationforadmission applicationforadmission) {
		this.applicationforadmission = applicationforadmission;
	}

	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	public Double getTotalFees() {
		return this.totalFees;
	}

	public void setTotalFees(Double totalFees) {
		this.totalFees = totalFees;
	}

	public Double getPaidFees() {
		return this.paidFees;
	}

	public void setPaidFees(Double paidFees) {
		this.paidFees = paidFees;
	}

	public Double getRemainingFees() {
		return this.remainingFees;
	}

	public void setRemainingFees(Double remainingFees) {
		this.remainingFees = remainingFees;
	}

	public Set getFeestransactions() {
		return this.feestransactions;
	}

	public void setFeestransactions(Set feestransactions) {
		this.feestransactions = feestransactions;
	}

}
