package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Subjects generated by hbm2java
 */
public class Subjects implements java.io.Serializable {

	private Integer subId;
	private Course course;
	private Branch branch;
	private Teacherdetail teacherdetail;
	private Integer semester;
	private String subCode;
	private String subName;
	private Set resultses = new HashSet(0);
	private Set teacherdetails = new HashSet(0);
	private Set examtimetables = new HashSet(0);

	public Subjects() {
	}

	public Subjects(Course course, Branch branch, Teacherdetail teacherdetail, Integer semester, String subCode,
			String subName, Set resultses, Set teacherdetails, Set examtimetables) {
		this.course = course;
		this.branch = branch;
		this.teacherdetail = teacherdetail;
		this.semester = semester;
		this.subCode = subCode;
		this.subName = subName;
		this.resultses = resultses;
		this.teacherdetails = teacherdetails;
		this.examtimetables = examtimetables;
	}

	public Integer getSubId() {
		return this.subId;
	}

	public void setSubId(Integer subId) {
		this.subId = subId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public Teacherdetail getTeacherdetail() {
		return this.teacherdetail;
	}

	public void setTeacherdetail(Teacherdetail teacherdetail) {
		this.teacherdetail = teacherdetail;
	}

	public Integer getSemester() {
		return this.semester;
	}

	public void setSemester(Integer semester) {
		this.semester = semester;
	}

	public String getSubCode() {
		return this.subCode;
	}

	public void setSubCode(String subCode) {
		this.subCode = subCode;
	}

	public String getSubName() {
		return this.subName;
	}

	public void setSubName(String subName) {
		this.subName = subName;
	}

	public Set getResultses() {
		return this.resultses;
	}

	public void setResultses(Set resultses) {
		this.resultses = resultses;
	}

	public Set getTeacherdetails() {
		return this.teacherdetails;
	}

	public void setTeacherdetails(Set teacherdetails) {
		this.teacherdetails = teacherdetails;
	}

	public Set getExamtimetables() {
		return this.examtimetables;
	}

	public void setExamtimetables(Set examtimetables) {
		this.examtimetables = examtimetables;
	}

}
