package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Syllabus generated by hbm2java
 */
public class Syllabus implements java.io.Serializable {

	private Integer syllabusId;
	private Teacherdetail teacherdetail;
	private String syllabusClass;
	private String syllabusSubject;
	private String syllabusModules;
	private String syllabusChapters;
	private String syllabusChapSubPoint;
	private String syllabusPracticals;
	private String syllabusTotalHours;
	private Date syllabusDate;

	public Syllabus() {
	}

	public Syllabus(Teacherdetail teacherdetail, String syllabusClass, String syllabusSubject, String syllabusModules,
			String syllabusChapters, String syllabusChapSubPoint, String syllabusPracticals, String syllabusTotalHours,
			Date syllabusDate) {
		this.teacherdetail = teacherdetail;
		this.syllabusClass = syllabusClass;
		this.syllabusSubject = syllabusSubject;
		this.syllabusModules = syllabusModules;
		this.syllabusChapters = syllabusChapters;
		this.syllabusChapSubPoint = syllabusChapSubPoint;
		this.syllabusPracticals = syllabusPracticals;
		this.syllabusTotalHours = syllabusTotalHours;
		this.syllabusDate = syllabusDate;
	}

	public Integer getSyllabusId() {
		return this.syllabusId;
	}

	public void setSyllabusId(Integer syllabusId) {
		this.syllabusId = syllabusId;
	}

	public Teacherdetail getTeacherdetail() {
		return this.teacherdetail;
	}

	public void setTeacherdetail(Teacherdetail teacherdetail) {
		this.teacherdetail = teacherdetail;
	}

	public String getSyllabusClass() {
		return this.syllabusClass;
	}

	public void setSyllabusClass(String syllabusClass) {
		this.syllabusClass = syllabusClass;
	}

	public String getSyllabusSubject() {
		return this.syllabusSubject;
	}

	public void setSyllabusSubject(String syllabusSubject) {
		this.syllabusSubject = syllabusSubject;
	}

	public String getSyllabusModules() {
		return this.syllabusModules;
	}

	public void setSyllabusModules(String syllabusModules) {
		this.syllabusModules = syllabusModules;
	}

	public String getSyllabusChapters() {
		return this.syllabusChapters;
	}

	public void setSyllabusChapters(String syllabusChapters) {
		this.syllabusChapters = syllabusChapters;
	}

	public String getSyllabusChapSubPoint() {
		return this.syllabusChapSubPoint;
	}

	public void setSyllabusChapSubPoint(String syllabusChapSubPoint) {
		this.syllabusChapSubPoint = syllabusChapSubPoint;
	}

	public String getSyllabusPracticals() {
		return this.syllabusPracticals;
	}

	public void setSyllabusPracticals(String syllabusPracticals) {
		this.syllabusPracticals = syllabusPracticals;
	}

	public String getSyllabusTotalHours() {
		return this.syllabusTotalHours;
	}

	public void setSyllabusTotalHours(String syllabusTotalHours) {
		this.syllabusTotalHours = syllabusTotalHours;
	}

	public Date getSyllabusDate() {
		return this.syllabusDate;
	}

	public void setSyllabusDate(Date syllabusDate) {
		this.syllabusDate = syllabusDate;
	}

}
