package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Teacherdetail generated by hbm2java
 */
public class Teacherdetail implements java.io.Serializable {

	private Integer teacherId;
	private Subjects subjects;
	private Branch branch;
	private String tcherFirstName;
	private String tcherMiddleName;
	private String tcherLastName;
	private String tcherEmailId;
	private String tcherPassword;
	private String tcherGender;
	private String tcherPhoneNumber;
	private String tcherPeremanantAddress;
	private String tcherQualification;
	private String tcherPreviousCollegeName;
	private Double tcherSalary;
	private String tcherExperience;
	private Set timetables = new HashSet(0);
	private Set loginstudentteachers = new HashSet(0);
	private Set subjectses = new HashSet(0);
	private Set assignments = new HashSet(0);
	private Set teacherattendances = new HashSet(0);
	private Set attendances = new HashSet(0);
	private Set syllabuses = new HashSet(0);
	private Set notices = new HashSet(0);
	private Set examtransactions = new HashSet(0);
	private Set invigilationdutieses = new HashSet(0);
	private Set inventoryrequests = new HashSet(0);

	public Teacherdetail() {
	}

	public Teacherdetail(Subjects subjects, Branch branch, String tcherFirstName, String tcherMiddleName,
			String tcherLastName, String tcherEmailId, String tcherPassword, String tcherGender,
			String tcherPhoneNumber, String tcherPeremanantAddress, String tcherQualification,
			String tcherPreviousCollegeName, Double tcherSalary, String tcherExperience, Set timetables,
			Set loginstudentteachers, Set subjectses, Set assignments, Set teacherattendances, Set attendances,
			Set syllabuses, Set notices, Set examtransactions, Set invigilationdutieses, Set inventoryrequests) {
		this.subjects = subjects;
		this.branch = branch;
		this.tcherFirstName = tcherFirstName;
		this.tcherMiddleName = tcherMiddleName;
		this.tcherLastName = tcherLastName;
		this.tcherEmailId = tcherEmailId;
		this.tcherPassword = tcherPassword;
		this.tcherGender = tcherGender;
		this.tcherPhoneNumber = tcherPhoneNumber;
		this.tcherPeremanantAddress = tcherPeremanantAddress;
		this.tcherQualification = tcherQualification;
		this.tcherPreviousCollegeName = tcherPreviousCollegeName;
		this.tcherSalary = tcherSalary;
		this.tcherExperience = tcherExperience;
		this.timetables = timetables;
		this.loginstudentteachers = loginstudentteachers;
		this.subjectses = subjectses;
		this.assignments = assignments;
		this.teacherattendances = teacherattendances;
		this.attendances = attendances;
		this.syllabuses = syllabuses;
		this.notices = notices;
		this.examtransactions = examtransactions;
		this.invigilationdutieses = invigilationdutieses;
		this.inventoryrequests = inventoryrequests;
	}

	public Integer getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	public Subjects getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Subjects subjects) {
		this.subjects = subjects;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public String getTcherFirstName() {
		return this.tcherFirstName;
	}

	public void setTcherFirstName(String tcherFirstName) {
		this.tcherFirstName = tcherFirstName;
	}

	public String getTcherMiddleName() {
		return this.tcherMiddleName;
	}

	public void setTcherMiddleName(String tcherMiddleName) {
		this.tcherMiddleName = tcherMiddleName;
	}

	public String getTcherLastName() {
		return this.tcherLastName;
	}

	public void setTcherLastName(String tcherLastName) {
		this.tcherLastName = tcherLastName;
	}

	public String getTcherEmailId() {
		return this.tcherEmailId;
	}

	public void setTcherEmailId(String tcherEmailId) {
		this.tcherEmailId = tcherEmailId;
	}

	public String getTcherPassword() {
		return this.tcherPassword;
	}

	public void setTcherPassword(String tcherPassword) {
		this.tcherPassword = tcherPassword;
	}

	public String getTcherGender() {
		return this.tcherGender;
	}

	public void setTcherGender(String tcherGender) {
		this.tcherGender = tcherGender;
	}

	public String getTcherPhoneNumber() {
		return this.tcherPhoneNumber;
	}

	public void setTcherPhoneNumber(String tcherPhoneNumber) {
		this.tcherPhoneNumber = tcherPhoneNumber;
	}

	public String getTcherPeremanantAddress() {
		return this.tcherPeremanantAddress;
	}

	public void setTcherPeremanantAddress(String tcherPeremanantAddress) {
		this.tcherPeremanantAddress = tcherPeremanantAddress;
	}

	public String getTcherQualification() {
		return this.tcherQualification;
	}

	public void setTcherQualification(String tcherQualification) {
		this.tcherQualification = tcherQualification;
	}

	public String getTcherPreviousCollegeName() {
		return this.tcherPreviousCollegeName;
	}

	public void setTcherPreviousCollegeName(String tcherPreviousCollegeName) {
		this.tcherPreviousCollegeName = tcherPreviousCollegeName;
	}

	public Double getTcherSalary() {
		return this.tcherSalary;
	}

	public void setTcherSalary(Double tcherSalary) {
		this.tcherSalary = tcherSalary;
	}

	public String getTcherExperience() {
		return this.tcherExperience;
	}

	public void setTcherExperience(String tcherExperience) {
		this.tcherExperience = tcherExperience;
	}

	public Set getTimetables() {
		return this.timetables;
	}

	public void setTimetables(Set timetables) {
		this.timetables = timetables;
	}

	public Set getLoginstudentteachers() {
		return this.loginstudentteachers;
	}

	public void setLoginstudentteachers(Set loginstudentteachers) {
		this.loginstudentteachers = loginstudentteachers;
	}

	public Set getSubjectses() {
		return this.subjectses;
	}

	public void setSubjectses(Set subjectses) {
		this.subjectses = subjectses;
	}

	public Set getAssignments() {
		return this.assignments;
	}

	public void setAssignments(Set assignments) {
		this.assignments = assignments;
	}

	public Set getTeacherattendances() {
		return this.teacherattendances;
	}

	public void setTeacherattendances(Set teacherattendances) {
		this.teacherattendances = teacherattendances;
	}

	public Set getAttendances() {
		return this.attendances;
	}

	public void setAttendances(Set attendances) {
		this.attendances = attendances;
	}

	public Set getSyllabuses() {
		return this.syllabuses;
	}

	public void setSyllabuses(Set syllabuses) {
		this.syllabuses = syllabuses;
	}

	public Set getNotices() {
		return this.notices;
	}

	public void setNotices(Set notices) {
		this.notices = notices;
	}

	public Set getExamtransactions() {
		return this.examtransactions;
	}

	public void setExamtransactions(Set examtransactions) {
		this.examtransactions = examtransactions;
	}

	public Set getInvigilationdutieses() {
		return this.invigilationdutieses;
	}

	public void setInvigilationdutieses(Set invigilationdutieses) {
		this.invigilationdutieses = invigilationdutieses;
	}

	public Set getInventoryrequests() {
		return this.inventoryrequests;
	}

	public void setInventoryrequests(Set inventoryrequests) {
		this.inventoryrequests = inventoryrequests;
	}

}
