package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private Integer teacherId;
	private String teachername;
	private Set hostelregistrations = new HashSet(0);

	public Teacher() {
	}

	public Teacher(String teachername, Set hostelregistrations) {
		this.teachername = teachername;
		this.hostelregistrations = hostelregistrations;
	}

	public Integer getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	public String getTeachername() {
		return this.teachername;
	}

	public void setTeachername(String teachername) {
		this.teachername = teachername;
	}

	public Set getHostelregistrations() {
		return this.hostelregistrations;
	}

	public void setHostelregistrations(Set hostelregistrations) {
		this.hostelregistrations = hostelregistrations;
	}

}
