package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Teacherroom generated by hbm2java
 */
public class Teacherroom implements java.io.Serializable {

	private Integer teacherRoomId;
	private Genderforhostelroom genderforhostelroom;
	private Set hostelroomsallots = new HashSet(0);

	public Teacherroom() {
	}

	public Teacherroom(Genderforhostelroom genderforhostelroom, Set hostelroomsallots) {
		this.genderforhostelroom = genderforhostelroom;
		this.hostelroomsallots = hostelroomsallots;
	}

	public Integer getTeacherRoomId() {
		return this.teacherRoomId;
	}

	public void setTeacherRoomId(Integer teacherRoomId) {
		this.teacherRoomId = teacherRoomId;
	}

	public Genderforhostelroom getGenderforhostelroom() {
		return this.genderforhostelroom;
	}

	public void setGenderforhostelroom(Genderforhostelroom genderforhostelroom) {
		this.genderforhostelroom = genderforhostelroom;
	}

	public Set getHostelroomsallots() {
		return this.hostelroomsallots;
	}

	public void setHostelroomsallots(Set hostelroomsallots) {
		this.hostelroomsallots = hostelroomsallots;
	}

}
