package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Timetable generated by hbm2java
 */
public class Timetable implements java.io.Serializable {

	private Integer timeTableId;
	private Subject subject;
	private Teacherdetail teacherdetail;
	private Classdetail classdetail;
	private Studentdetail studentdetail;
	private String timeTableDay;
	private Date timeTableDate;
	private Date timeTableTime;

	public Timetable() {
	}

	public Timetable(Subject subject, Teacherdetail teacherdetail, Classdetail classdetail,
			Studentdetail studentdetail, String timeTableDay, Date timeTableDate, Date timeTableTime) {
		this.subject = subject;
		this.teacherdetail = teacherdetail;
		this.classdetail = classdetail;
		this.studentdetail = studentdetail;
		this.timeTableDay = timeTableDay;
		this.timeTableDate = timeTableDate;
		this.timeTableTime = timeTableTime;
	}

	public Integer getTimeTableId() {
		return this.timeTableId;
	}

	public void setTimeTableId(Integer timeTableId) {
		this.timeTableId = timeTableId;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public Teacherdetail getTeacherdetail() {
		return this.teacherdetail;
	}

	public void setTeacherdetail(Teacherdetail teacherdetail) {
		this.teacherdetail = teacherdetail;
	}

	public Classdetail getClassdetail() {
		return this.classdetail;
	}

	public void setClassdetail(Classdetail classdetail) {
		this.classdetail = classdetail;
	}

	public Studentdetail getStudentdetail() {
		return this.studentdetail;
	}

	public void setStudentdetail(Studentdetail studentdetail) {
		this.studentdetail = studentdetail;
	}

	public String getTimeTableDay() {
		return this.timeTableDay;
	}

	public void setTimeTableDay(String timeTableDay) {
		this.timeTableDay = timeTableDay;
	}

	public Date getTimeTableDate() {
		return this.timeTableDate;
	}

	public void setTimeTableDate(Date timeTableDate) {
		this.timeTableDate = timeTableDate;
	}

	public Date getTimeTableTime() {
		return this.timeTableTime;
	}

	public void setTimeTableTime(Date timeTableTime) {
		this.timeTableTime = timeTableTime;
	}

}
