package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Transportservicereq generated by hbm2java
 */
public class Transportservicereq implements java.io.Serializable {

	private Integer transportServiceReqId;
	private Enrolledstudents enrolledstudents;
	private Busandstop busandstop;
	private Date passValidityStartDate;
	private Date passValidityEndtDate;
	private String passValidityMonths;
	private Long amountPaid;
	private byte[] studentPhoto;
	private Integer status;

	public Transportservicereq() {
	}

	public Transportservicereq(Enrolledstudents enrolledstudents, Busandstop busandstop, Date passValidityStartDate,
			Date passValidityEndtDate, String passValidityMonths, Long amountPaid, byte[] studentPhoto, Integer status) {
		this.enrolledstudents = enrolledstudents;
		this.busandstop = busandstop;
		this.passValidityStartDate = passValidityStartDate;
		this.passValidityEndtDate = passValidityEndtDate;
		this.passValidityMonths = passValidityMonths;
		this.amountPaid = amountPaid;
		this.studentPhoto = studentPhoto;
		this.status = status;
	}

	public Integer getTransportServiceReqId() {
		return this.transportServiceReqId;
	}

	public void setTransportServiceReqId(Integer transportServiceReqId) {
		this.transportServiceReqId = transportServiceReqId;
	}

	public Enrolledstudents getEnrolledstudents() {
		return this.enrolledstudents;
	}

	public void setEnrolledstudents(Enrolledstudents enrolledstudents) {
		this.enrolledstudents = enrolledstudents;
	}

	public Busandstop getBusandstop() {
		return this.busandstop;
	}

	public void setBusandstop(Busandstop busandstop) {
		this.busandstop = busandstop;
	}

	public Date getPassValidityStartDate() {
		return this.passValidityStartDate;
	}

	public void setPassValidityStartDate(Date passValidityStartDate) {
		this.passValidityStartDate = passValidityStartDate;
	}

	public Date getPassValidityEndtDate() {
		return this.passValidityEndtDate;
	}

	public void setPassValidityEndtDate(Date passValidityEndtDate) {
		this.passValidityEndtDate = passValidityEndtDate;
	}

	public String getPassValidityMonths() {
		return this.passValidityMonths;
	}

	public void setPassValidityMonths(String passValidityMonths) {
		this.passValidityMonths = passValidityMonths;
	}

	public Long getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(Long amountPaid) {
		this.amountPaid = amountPaid;
	}

	public byte[] getStudentPhoto() {
		return this.studentPhoto;
	}

	public void setStudentPhoto(byte[] studentPhoto) {
		this.studentPhoto = studentPhoto;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
