package com.pojo;

// Generated Mar 3, 2017 4:37:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Uploadeddocuments generated by hbm2java
 */
public class Uploadeddocuments implements java.io.Serializable {

	private Integer uploadedDocId;
	private byte[] photograph;
	private byte[] signature;
	private byte[] ageProof;
	private byte[] sscmarksheet;
	private byte[] hscmarksheet;
	private byte[] casteCategoryCertificate;
	private byte[] bplcertificate;
	private byte[] diplomaCertificate;
	private byte[] bachelorDegreeCertificate;
	private byte[] mastersDegreeCertificate;
	private Set applicationforadmissions = new HashSet(0);

	public Uploadeddocuments() {
	}

	public Uploadeddocuments(byte[] photograph, byte[] signature, byte[] ageProof, byte[] sscmarksheet,
			byte[] hscmarksheet, byte[] casteCategoryCertificate, byte[] bplcertificate, byte[] diplomaCertificate,
			byte[] bachelorDegreeCertificate, byte[] mastersDegreeCertificate, Set applicationforadmissions) {
		this.photograph = photograph;
		this.signature = signature;
		this.ageProof = ageProof;
		this.sscmarksheet = sscmarksheet;
		this.hscmarksheet = hscmarksheet;
		this.casteCategoryCertificate = casteCategoryCertificate;
		this.bplcertificate = bplcertificate;
		this.diplomaCertificate = diplomaCertificate;
		this.bachelorDegreeCertificate = bachelorDegreeCertificate;
		this.mastersDegreeCertificate = mastersDegreeCertificate;
		this.applicationforadmissions = applicationforadmissions;
	}

	public Integer getUploadedDocId() {
		return this.uploadedDocId;
	}

	public void setUploadedDocId(Integer uploadedDocId) {
		this.uploadedDocId = uploadedDocId;
	}

	public byte[] getPhotograph() {
		return this.photograph;
	}

	public void setPhotograph(byte[] photograph) {
		this.photograph = photograph;
	}

	public byte[] getSignature() {
		return this.signature;
	}

	public void setSignature(byte[] signature) {
		this.signature = signature;
	}

	public byte[] getAgeProof() {
		return this.ageProof;
	}

	public void setAgeProof(byte[] ageProof) {
		this.ageProof = ageProof;
	}

	public byte[] getSscmarksheet() {
		return this.sscmarksheet;
	}

	public void setSscmarksheet(byte[] sscmarksheet) {
		this.sscmarksheet = sscmarksheet;
	}

	public byte[] getHscmarksheet() {
		return this.hscmarksheet;
	}

	public void setHscmarksheet(byte[] hscmarksheet) {
		this.hscmarksheet = hscmarksheet;
	}

	public byte[] getCasteCategoryCertificate() {
		return this.casteCategoryCertificate;
	}

	public void setCasteCategoryCertificate(byte[] casteCategoryCertificate) {
		this.casteCategoryCertificate = casteCategoryCertificate;
	}

	public byte[] getBplcertificate() {
		return this.bplcertificate;
	}

	public void setBplcertificate(byte[] bplcertificate) {
		this.bplcertificate = bplcertificate;
	}

	public byte[] getDiplomaCertificate() {
		return this.diplomaCertificate;
	}

	public void setDiplomaCertificate(byte[] diplomaCertificate) {
		this.diplomaCertificate = diplomaCertificate;
	}

	public byte[] getBachelorDegreeCertificate() {
		return this.bachelorDegreeCertificate;
	}

	public void setBachelorDegreeCertificate(byte[] bachelorDegreeCertificate) {
		this.bachelorDegreeCertificate = bachelorDegreeCertificate;
	}

	public byte[] getMastersDegreeCertificate() {
		return this.mastersDegreeCertificate;
	}

	public void setMastersDegreeCertificate(byte[] mastersDegreeCertificate) {
		this.mastersDegreeCertificate = mastersDegreeCertificate;
	}

	public Set getApplicationforadmissions() {
		return this.applicationforadmissions;
	}

	public void setApplicationforadmissions(Set applicationforadmissions) {
		this.applicationforadmissions = applicationforadmissions;
	}

}
